-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_conv_2d_cl_array_array_ap_fixed_42_16_5_3_0_32u_config18_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer17_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    layer17_out_empty_n : IN STD_LOGIC;
    layer17_out_read : OUT STD_LOGIC;
    layer18_out_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
    layer18_out_full_n : IN STD_LOGIC;
    layer18_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_conv_2d_cl_array_array_ap_fixed_42_16_5_3_0_32u_config18_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_C40 : STD_LOGIC_VECTOR (11 downto 0) := "110001000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer17_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln51_fu_1647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln51_fu_1641_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_reg_1999 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal trunc_ln145_fu_1653_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_reg_2007 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_s_reg_2012 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_147_reg_2017 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_148_reg_2022 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_149_reg_2027 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_150_reg_2032 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_151_reg_2037 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_152_reg_2042 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_153_reg_2047 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_154_reg_2052 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_155_reg_2057 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_156_reg_2062 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_157_reg_2067 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_158_reg_2072 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_159_reg_2077 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_160_reg_2082 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_161_reg_2087 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_162_reg_2092 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_163_reg_2097 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_164_reg_2102 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_165_reg_2107 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_166_reg_2112 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_167_reg_2117 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_168_reg_2122 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_169_reg_2127 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_170_reg_2132 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_171_reg_2137 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_172_reg_2142 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_173_reg_2147 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_174_reg_2152 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_175_reg_2157 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_176_reg_2162 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din : STD_LOGIC_VECTOR (2047 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write : STD_LOGIC;
    signal indvar_flatten_reg_878 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call36 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer18_out_din : OUT STD_LOGIC_VECTOR (2047 downto 0);
        layer18_out_full_n : IN STD_LOGIC;
        layer18_out_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889 : component myproject_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start,
        ap_done => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done,
        ap_idle => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_idle,
        ap_ready => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready,
        layer18_out_din => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din,
        layer18_out_full_n => layer18_out_full_n,
        layer18_out_write => grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write,
        p_read => trunc_ln145_reg_2007,
        p_read1 => trunc_ln145_s_reg_2012,
        p_read2 => trunc_ln145_147_reg_2017,
        p_read3 => trunc_ln145_148_reg_2022,
        p_read4 => trunc_ln145_149_reg_2027,
        p_read5 => trunc_ln145_150_reg_2032,
        p_read6 => trunc_ln145_151_reg_2037,
        p_read7 => trunc_ln145_152_reg_2042,
        p_read8 => trunc_ln145_153_reg_2047,
        p_read9 => trunc_ln145_154_reg_2052,
        p_read10 => trunc_ln145_155_reg_2057,
        p_read11 => trunc_ln145_156_reg_2062,
        p_read12 => trunc_ln145_157_reg_2067,
        p_read13 => trunc_ln145_158_reg_2072,
        p_read14 => trunc_ln145_159_reg_2077,
        p_read15 => trunc_ln145_160_reg_2082,
        p_read16 => trunc_ln145_161_reg_2087,
        p_read17 => trunc_ln145_162_reg_2092,
        p_read18 => trunc_ln145_163_reg_2097,
        p_read19 => trunc_ln145_164_reg_2102,
        p_read20 => trunc_ln145_165_reg_2107,
        p_read21 => trunc_ln145_166_reg_2112,
        p_read22 => trunc_ln145_167_reg_2117,
        p_read23 => trunc_ln145_168_reg_2122,
        p_read24 => trunc_ln145_169_reg_2127,
        p_read25 => trunc_ln145_170_reg_2132,
        p_read26 => trunc_ln145_171_reg_2137,
        p_read27 => trunc_ln145_172_reg_2142,
        p_read28 => trunc_ln145_173_reg_2147,
        p_read29 => trunc_ln145_174_reg_2152,
        p_read30 => trunc_ln145_175_reg_2157,
        p_read31 => trunc_ln145_176_reg_2162);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_878_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done = ap_const_logic_1))) then 
                indvar_flatten_reg_878 <= add_ln51_reg_1999;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_878 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln51_reg_1999 <= add_ln51_fu_1641_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln145_147_reg_2017 <= layer17_out_dout(47 downto 32);
                trunc_ln145_148_reg_2022 <= layer17_out_dout(63 downto 48);
                trunc_ln145_149_reg_2027 <= layer17_out_dout(79 downto 64);
                trunc_ln145_150_reg_2032 <= layer17_out_dout(95 downto 80);
                trunc_ln145_151_reg_2037 <= layer17_out_dout(111 downto 96);
                trunc_ln145_152_reg_2042 <= layer17_out_dout(127 downto 112);
                trunc_ln145_153_reg_2047 <= layer17_out_dout(143 downto 128);
                trunc_ln145_154_reg_2052 <= layer17_out_dout(159 downto 144);
                trunc_ln145_155_reg_2057 <= layer17_out_dout(175 downto 160);
                trunc_ln145_156_reg_2062 <= layer17_out_dout(191 downto 176);
                trunc_ln145_157_reg_2067 <= layer17_out_dout(207 downto 192);
                trunc_ln145_158_reg_2072 <= layer17_out_dout(223 downto 208);
                trunc_ln145_159_reg_2077 <= layer17_out_dout(239 downto 224);
                trunc_ln145_160_reg_2082 <= layer17_out_dout(255 downto 240);
                trunc_ln145_161_reg_2087 <= layer17_out_dout(271 downto 256);
                trunc_ln145_162_reg_2092 <= layer17_out_dout(287 downto 272);
                trunc_ln145_163_reg_2097 <= layer17_out_dout(303 downto 288);
                trunc_ln145_164_reg_2102 <= layer17_out_dout(319 downto 304);
                trunc_ln145_165_reg_2107 <= layer17_out_dout(335 downto 320);
                trunc_ln145_166_reg_2112 <= layer17_out_dout(351 downto 336);
                trunc_ln145_167_reg_2117 <= layer17_out_dout(367 downto 352);
                trunc_ln145_168_reg_2122 <= layer17_out_dout(383 downto 368);
                trunc_ln145_169_reg_2127 <= layer17_out_dout(399 downto 384);
                trunc_ln145_170_reg_2132 <= layer17_out_dout(415 downto 400);
                trunc_ln145_171_reg_2137 <= layer17_out_dout(431 downto 416);
                trunc_ln145_172_reg_2142 <= layer17_out_dout(447 downto 432);
                trunc_ln145_173_reg_2147 <= layer17_out_dout(463 downto 448);
                trunc_ln145_174_reg_2152 <= layer17_out_dout(479 downto 464);
                trunc_ln145_175_reg_2157 <= layer17_out_dout(495 downto 480);
                trunc_ln145_176_reg_2162 <= layer17_out_dout(511 downto 496);
                trunc_ln145_reg_2007 <= trunc_ln145_fu_1653_p1;
                trunc_ln145_s_reg_2012 <= layer17_out_dout(31 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer17_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_1647_p2, grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln51_fu_1641_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_878) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(layer17_out_empty_n, icmp_ln51_fu_1647_p2)
    begin
                ap_block_state2 <= ((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call36_assign_proc : process(layer17_out_empty_n, icmp_ln51_fu_1647_p2)
    begin
                ap_block_state2_ignore_call36 <= ((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer17_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_1647_p2)
    begin
        if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start <= grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg;
    icmp_ln51_fu_1647_p2 <= "1" when (indvar_flatten_reg_878 = ap_const_lv12_C40) else "0";

    internal_ap_ready_assign_proc : process(layer17_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_1647_p2)
    begin
        if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer17_out_blk_n_assign_proc : process(layer17_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_1647_p2)
    begin
        if (((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer17_out_blk_n <= layer17_out_empty_n;
        else 
            layer17_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer17_out_read_assign_proc : process(layer17_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_1647_p2)
    begin
        if ((not(((icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (layer17_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_1647_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer17_out_read <= ap_const_logic_1;
        else 
            layer17_out_read <= ap_const_logic_0;
        end if; 
    end process;

    layer18_out_din <= grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din;

    layer18_out_write_assign_proc : process(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer18_out_write <= grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write;
        else 
            layer18_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln145_fu_1653_p1 <= layer17_out_dout(16 - 1 downto 0);
end behav;
