-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_14_5_3_0_16u_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer5_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    layer5_out_empty_n : IN STD_LOGIC;
    layer5_out_read : OUT STD_LOGIC;
    layer6_out_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
    layer6_out_full_n : IN STD_LOGIC;
    layer6_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_14_5_3_0_16u_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_F04 : STD_LOGIC_VECTOR (11 downto 0) := "111100000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln51_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln51_fu_469_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln51_reg_563 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal trunc_ln145_fu_481_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_reg_571 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_s_reg_576 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_110_reg_581 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_111_reg_586 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_112_reg_591 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_113_reg_596 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_114_reg_601 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln145_115_reg_606 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din : STD_LOGIC_VECTOR (1023 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write : STD_LOGIC;
    signal indvar_flatten_reg_256 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call12 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer6_out_din : OUT STD_LOGIC_VECTOR (1023 downto 0);
        layer6_out_full_n : IN STD_LOGIC;
        layer6_out_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267 : component myproject_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start,
        ap_done => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done,
        ap_idle => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_idle,
        ap_ready => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready,
        layer6_out_din => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din,
        layer6_out_full_n => layer6_out_full_n,
        layer6_out_write => grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write,
        p_read => trunc_ln145_reg_571,
        p_read1 => trunc_ln145_s_reg_576,
        p_read2 => trunc_ln145_110_reg_581,
        p_read3 => trunc_ln145_111_reg_586,
        p_read4 => trunc_ln145_112_reg_591,
        p_read5 => trunc_ln145_113_reg_596,
        p_read6 => trunc_ln145_114_reg_601,
        p_read7 => trunc_ln145_115_reg_606);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                indvar_flatten_reg_256 <= add_ln51_reg_563;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_256 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln51_reg_563 <= add_ln51_fu_469_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln145_110_reg_581 <= layer5_out_dout(47 downto 32);
                trunc_ln145_111_reg_586 <= layer5_out_dout(63 downto 48);
                trunc_ln145_112_reg_591 <= layer5_out_dout(79 downto 64);
                trunc_ln145_113_reg_596 <= layer5_out_dout(95 downto 80);
                trunc_ln145_114_reg_601 <= layer5_out_dout(111 downto 96);
                trunc_ln145_115_reg_606 <= layer5_out_dout(127 downto 112);
                trunc_ln145_reg_571 <= trunc_ln145_fu_481_p1;
                trunc_ln145_s_reg_576 <= layer5_out_dout(31 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer5_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_475_p2, grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln51_fu_469_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_256) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(layer5_out_empty_n, icmp_ln51_fu_475_p2)
    begin
                ap_block_state2 <= ((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call12_assign_proc : process(layer5_out_empty_n, icmp_ln51_fu_475_p2)
    begin
                ap_block_state2_ignore_call12 <= ((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer5_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_475_p2)
    begin
        if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start <= grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg;
    icmp_ln51_fu_475_p2 <= "1" when (indvar_flatten_reg_256 = ap_const_lv12_F04) else "0";

    internal_ap_ready_assign_proc : process(layer5_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_475_p2)
    begin
        if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(layer5_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_475_p2)
    begin
        if (((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer5_out_blk_n <= layer5_out_empty_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer5_out_read_assign_proc : process(layer5_out_empty_n, ap_CS_fsm_state2, icmp_ln51_fu_475_p2)
    begin
        if ((not(((icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (layer5_out_empty_n = ap_const_logic_0))) and (icmp_ln51_fu_475_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer5_out_read <= ap_const_logic_1;
        else 
            layer5_out_read <= ap_const_logic_0;
        end if; 
    end process;

    layer6_out_din <= grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din;

    layer6_out_write_assign_proc : process(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer6_out_write <= grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write;
        else 
            layer6_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln145_fu_481_p1 <= layer5_out_dout(16 - 1 downto 0);
end behav;
