// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_38_12_5_3_0_8u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write,
        p_read,
        p_read1,
        p_read2
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [511:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer2_out_write;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] kernel_data_V_10_3;
reg   [15:0] kernel_data_V_10_0;
reg   [15:0] kernel_data_V_10_4;
reg   [15:0] kernel_data_V_10_1;
reg   [15:0] kernel_data_V_10_5;
reg   [15:0] kernel_data_V_10_2;
reg   [15:0] kernel_data_V_10_12;
reg   [15:0] kernel_data_V_10_9;
reg   [15:0] kernel_data_V_10_13;
reg   [15:0] kernel_data_V_10_10;
reg   [15:0] kernel_data_V_10_14;
reg   [15:0] kernel_data_V_10_11;
reg   [15:0] kernel_data_V_10_21;
reg   [15:0] kernel_data_V_10_18;
reg   [15:0] kernel_data_V_10_22;
reg   [15:0] kernel_data_V_10_19;
reg   [15:0] kernel_data_V_10_23;
reg   [15:0] kernel_data_V_10_20;
reg   [15:0] kernel_data_V_10_6;
reg   [15:0] kernel_data_V_10_7;
reg   [15:0] kernel_data_V_10_8;
reg   [15:0] kernel_data_V_10_15;
reg   [15:0] kernel_data_V_10_16;
reg   [15:0] kernel_data_V_10_17;
reg   [15:0] kernel_data_V_10_24;
reg   [15:0] kernel_data_V_10_25;
reg   [15:0] kernel_data_V_10_26;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln284_reg_522;
reg   [0:0] and_ln284_2_reg_536;
wire   [0:0] icmp_ln284_fu_290_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln284_2_fu_347_p2;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_done;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_idle;
wire    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_ready;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_0;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_1;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_2;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_3;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_4;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_5;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_6;
wire   [37:0] grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_7;
reg    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_start;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_done;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_idle;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_ready;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o_ap_vld;
wire   [15:0] call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o_ap_vld;
reg    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg;
wire   [31:0] select_ln318_fu_446_p3;
reg    ap_predicate_op35_write_state3;
reg    ap_block_state3;
reg    ap_predicate_op24_call_state3;
reg    ap_block_state3_on_subcall_done;
wire   [0:0] icmp_ln303_fu_429_p2;
wire   [31:0] select_ln313_fu_493_p3;
wire   [0:0] icmp_ln307_fu_476_p2;
wire   [31:0] add_ln307_fu_471_p2;
wire   [31:0] add_ln303_fu_424_p2;
wire   [30:0] tmp_54_fu_309_p4;
wire   [30:0] tmp_55_fu_325_p4;
wire   [0:0] icmp_ln284_15_fu_319_p2;
wire   [0:0] icmp_ln284_16_fu_335_p2;
wire   [0:0] and_ln284_fu_341_p2;
wire   [0:0] grp_fu_281_p2;
wire   [485:0] tmp_fu_385_p16;
wire   [31:0] add_ln318_fu_441_p2;
wire   [31:0] add_ln313_fu_488_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_condition_374;
reg    ap_condition_380;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 kernel_data_V_10_3 = 16'd0;
#0 kernel_data_V_10_0 = 16'd0;
#0 kernel_data_V_10_4 = 16'd0;
#0 kernel_data_V_10_1 = 16'd0;
#0 kernel_data_V_10_5 = 16'd0;
#0 kernel_data_V_10_2 = 16'd0;
#0 kernel_data_V_10_12 = 16'd0;
#0 kernel_data_V_10_9 = 16'd0;
#0 kernel_data_V_10_13 = 16'd0;
#0 kernel_data_V_10_10 = 16'd0;
#0 kernel_data_V_10_14 = 16'd0;
#0 kernel_data_V_10_11 = 16'd0;
#0 kernel_data_V_10_21 = 16'd0;
#0 kernel_data_V_10_18 = 16'd0;
#0 kernel_data_V_10_22 = 16'd0;
#0 kernel_data_V_10_19 = 16'd0;
#0 kernel_data_V_10_23 = 16'd0;
#0 kernel_data_V_10_20 = 16'd0;
#0 kernel_data_V_10_6 = 16'd0;
#0 kernel_data_V_10_7 = 16'd0;
#0 kernel_data_V_10_8 = 16'd0;
#0 kernel_data_V_10_15 = 16'd0;
#0 kernel_data_V_10_16 = 16'd0;
#0 kernel_data_V_10_17 = 16'd0;
#0 kernel_data_V_10_24 = 16'd0;
#0 kernel_data_V_10_25 = 16'd0;
#0 kernel_data_V_10_26 = 16'd0;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg = 1'b0;
end

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start),
    .ap_done(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_done),
    .ap_idle(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_idle),
    .ap_ready(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_ready),
    .kernel_data_V_10_0(kernel_data_V_10_0),
    .kernel_data_V_10_1(kernel_data_V_10_1),
    .kernel_data_V_10_2(kernel_data_V_10_2),
    .kernel_data_V_10_3(kernel_data_V_10_3),
    .kernel_data_V_10_4(kernel_data_V_10_4),
    .kernel_data_V_10_5(kernel_data_V_10_5),
    .kernel_data_V_10_6(kernel_data_V_10_6),
    .kernel_data_V_10_7(kernel_data_V_10_7),
    .kernel_data_V_10_8(kernel_data_V_10_8),
    .kernel_data_V_10_9(kernel_data_V_10_9),
    .kernel_data_V_10_10(kernel_data_V_10_10),
    .kernel_data_V_10_11(kernel_data_V_10_11),
    .kernel_data_V_10_12(kernel_data_V_10_12),
    .kernel_data_V_10_13(kernel_data_V_10_13),
    .kernel_data_V_10_14(kernel_data_V_10_14),
    .kernel_data_V_10_15(kernel_data_V_10_15),
    .kernel_data_V_10_16(kernel_data_V_10_16),
    .kernel_data_V_10_17(kernel_data_V_10_17),
    .kernel_data_V_10_18(kernel_data_V_10_18),
    .kernel_data_V_10_19(kernel_data_V_10_19),
    .kernel_data_V_10_20(kernel_data_V_10_20),
    .kernel_data_V_10_21(kernel_data_V_10_21),
    .kernel_data_V_10_22(kernel_data_V_10_22),
    .kernel_data_V_10_23(kernel_data_V_10_23),
    .kernel_data_V_10_24(kernel_data_V_10_24),
    .kernel_data_V_10_25(kernel_data_V_10_25),
    .kernel_data_V_10_26(kernel_data_V_10_26),
    .ap_return_0(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_0),
    .ap_return_1(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_1),
    .ap_return_2(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_2),
    .ap_return_3(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_3),
    .ap_return_4(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_4),
    .ap_return_5(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_5),
    .ap_return_6(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_6),
    .ap_return_7(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_7)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_start),
    .ap_done(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_done),
    .ap_idle(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_idle),
    .ap_ready(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .kernel_data_V_10_3_i(kernel_data_V_10_3),
    .kernel_data_V_10_3_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o),
    .kernel_data_V_10_3_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o_ap_vld),
    .kernel_data_V_10_0(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0),
    .kernel_data_V_10_0_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0_ap_vld),
    .kernel_data_V_10_4_i(kernel_data_V_10_4),
    .kernel_data_V_10_4_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o),
    .kernel_data_V_10_4_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o_ap_vld),
    .kernel_data_V_10_1(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1),
    .kernel_data_V_10_1_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1_ap_vld),
    .kernel_data_V_10_5_i(kernel_data_V_10_5),
    .kernel_data_V_10_5_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o),
    .kernel_data_V_10_5_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o_ap_vld),
    .kernel_data_V_10_2(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2),
    .kernel_data_V_10_2_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2_ap_vld),
    .kernel_data_V_10_12_i(kernel_data_V_10_12),
    .kernel_data_V_10_12_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o),
    .kernel_data_V_10_12_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o_ap_vld),
    .kernel_data_V_10_9(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9),
    .kernel_data_V_10_9_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9_ap_vld),
    .kernel_data_V_10_13_i(kernel_data_V_10_13),
    .kernel_data_V_10_13_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o),
    .kernel_data_V_10_13_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o_ap_vld),
    .kernel_data_V_10_10(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10),
    .kernel_data_V_10_10_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10_ap_vld),
    .kernel_data_V_10_14_i(kernel_data_V_10_14),
    .kernel_data_V_10_14_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o),
    .kernel_data_V_10_14_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o_ap_vld),
    .kernel_data_V_10_11(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11),
    .kernel_data_V_10_11_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11_ap_vld),
    .kernel_data_V_10_21_i(kernel_data_V_10_21),
    .kernel_data_V_10_21_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o),
    .kernel_data_V_10_21_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o_ap_vld),
    .kernel_data_V_10_18(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18),
    .kernel_data_V_10_18_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18_ap_vld),
    .kernel_data_V_10_22_i(kernel_data_V_10_22),
    .kernel_data_V_10_22_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o),
    .kernel_data_V_10_22_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o_ap_vld),
    .kernel_data_V_10_19(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19),
    .kernel_data_V_10_19_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19_ap_vld),
    .kernel_data_V_10_23_i(kernel_data_V_10_23),
    .kernel_data_V_10_23_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o),
    .kernel_data_V_10_23_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o_ap_vld),
    .kernel_data_V_10_20(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20),
    .kernel_data_V_10_20_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20_ap_vld),
    .kernel_data_V_10_6_i(kernel_data_V_10_6),
    .kernel_data_V_10_6_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o),
    .kernel_data_V_10_6_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o_ap_vld),
    .kernel_data_V_10_7_i(kernel_data_V_10_7),
    .kernel_data_V_10_7_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o),
    .kernel_data_V_10_7_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o_ap_vld),
    .kernel_data_V_10_8_i(kernel_data_V_10_8),
    .kernel_data_V_10_8_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o),
    .kernel_data_V_10_8_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o_ap_vld),
    .kernel_data_V_10_15_i(kernel_data_V_10_15),
    .kernel_data_V_10_15_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o),
    .kernel_data_V_10_15_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o_ap_vld),
    .kernel_data_V_10_16_i(kernel_data_V_10_16),
    .kernel_data_V_10_16_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o),
    .kernel_data_V_10_16_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o_ap_vld),
    .kernel_data_V_10_17_i(kernel_data_V_10_17),
    .kernel_data_V_10_17_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o),
    .kernel_data_V_10_17_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o_ap_vld),
    .kernel_data_V_10_24_i(kernel_data_V_10_24),
    .kernel_data_V_10_24_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o),
    .kernel_data_V_10_24_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o_ap_vld),
    .kernel_data_V_10_25_i(kernel_data_V_10_25),
    .kernel_data_V_10_25_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o),
    .kernel_data_V_10_25_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o_ap_vld),
    .kernel_data_V_10_26_i(kernel_data_V_10_26),
    .kernel_data_V_10_26_o(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o),
    .kernel_data_V_10_26_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln284_fu_290_p2 == 1'd1) & (1'd1 == and_ln284_2_fu_347_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_374)) begin
        if ((icmp_ln303_fu_429_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_429_p2 == 1'd0)) begin
            pX_2 <= add_ln303_fu_424_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_380)) begin
        if ((icmp_ln307_fu_476_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln307_fu_476_p2 == 1'd0)) begin
            pY_2 <= add_ln307_fu_471_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_374)) begin
        if ((icmp_ln303_fu_429_p2 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln303_fu_429_p2 == 1'd0)) begin
            sX_2 <= select_ln318_fu_446_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_380)) begin
        if ((icmp_ln307_fu_476_p2 == 1'd1)) begin
            sY_2 <= 32'd0;
        end else if ((icmp_ln307_fu_476_p2 == 1'd0)) begin
            sY_2 <= select_ln313_fu_493_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln284_fu_290_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln284_2_reg_536 <= and_ln284_2_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln284_reg_522 <= icmp_ln284_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0_ap_vld == 1'b1))) begin
        kernel_data_V_10_0 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1_ap_vld == 1'b1))) begin
        kernel_data_V_10_1 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10_ap_vld == 1'b1))) begin
        kernel_data_V_10_10 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11_ap_vld == 1'b1))) begin
        kernel_data_V_10_11 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_12 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_13 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_14 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_15 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_15_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_16 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_17 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18_ap_vld == 1'b1))) begin
        kernel_data_V_10_18 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_18;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19_ap_vld == 1'b1))) begin
        kernel_data_V_10_19 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_19;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2_ap_vld == 1'b1))) begin
        kernel_data_V_10_2 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20_ap_vld == 1'b1))) begin
        kernel_data_V_10_20 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_20;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_21 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_21_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_22 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_22_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_23 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_23_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_24 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_24_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_10_25 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_25_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_10_26 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_26_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_3 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_4 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_5 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_6 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_7 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o_ap_vld == 1'b1))) begin
        kernel_data_V_10_8 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9_ap_vld == 1'b1))) begin
        kernel_data_V_10_9 <= call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_kernel_data_V_10_9;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_start = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_fixed_16_3_5_3_0_3u_config2_s_fu_205_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln284_2_reg_536) & (icmp_ln284_reg_522 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (ap_predicate_op35_write_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln303_fu_424_p2 = (pX_2 + 32'd1);

assign add_ln307_fu_471_p2 = (pY_2 + 32'd1);

assign add_ln313_fu_488_p2 = (sY_2 + 32'd1);

assign add_ln318_fu_441_p2 = (sX_2 + 32'd1);

assign and_ln284_2_fu_347_p2 = (grp_fu_281_p2 & and_ln284_fu_341_p2);

assign and_ln284_fu_341_p2 = (icmp_ln284_16_fu_335_p2 & icmp_ln284_15_fu_319_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state3 = ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_done == 1'b0) & (ap_predicate_op24_call_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_374 = (~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_condition_380 = (~((1'b1 == ap_block_state3_on_subcall_done) | ((ap_predicate_op35_write_state3 == 1'b1) & (layer2_out_full_n == 1'b0))) & (icmp_ln303_fu_429_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_predicate_op24_call_state3 = ((1'd1 == and_ln284_2_reg_536) & (icmp_ln284_reg_522 == 1'd1));
end

always @ (*) begin
    ap_predicate_op35_write_state3 = ((1'd1 == and_ln284_2_reg_536) & (icmp_ln284_reg_522 == 1'd1));
end

assign grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start = grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_start_reg;

assign grp_fu_281_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln284_15_fu_319_p2 = (($signed(tmp_54_fu_309_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_16_fu_335_p2 = (($signed(tmp_55_fu_325_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_290_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_429_p2 = ((add_ln303_fu_424_p2 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_476_p2 = ((add_ln307_fu_471_p2 == 32'd64) ? 1'b1 : 1'b0);

assign layer2_out_din = tmp_fu_385_p16;

assign select_ln313_fu_493_p3 = ((grp_fu_281_p2[0:0] == 1'b1) ? 32'd2 : add_ln313_fu_488_p2);

assign select_ln318_fu_446_p3 = ((icmp_ln284_reg_522[0:0] == 1'b1) ? 32'd2 : add_ln318_fu_441_p2);

assign tmp_54_fu_309_p4 = {{pY_2[31:1]}};

assign tmp_55_fu_325_p4 = {{pX_2[31:1]}};

assign tmp_fu_385_p16 = {{{{{{{{{{{{{{{grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_7}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_6}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_5}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_4}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_3}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_2}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_1}}, {26'd0}}, {grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_fu_143_ap_return_0}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_38_12_5_3_0_8u_config2_s
