// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kernel_data_V_10_0,
        kernel_data_V_10_1,
        kernel_data_V_10_2,
        kernel_data_V_10_3,
        kernel_data_V_10_4,
        kernel_data_V_10_5,
        kernel_data_V_10_6,
        kernel_data_V_10_7,
        kernel_data_V_10_8,
        kernel_data_V_10_9,
        kernel_data_V_10_10,
        kernel_data_V_10_11,
        kernel_data_V_10_12,
        kernel_data_V_10_13,
        kernel_data_V_10_14,
        kernel_data_V_10_15,
        kernel_data_V_10_16,
        kernel_data_V_10_17,
        kernel_data_V_10_18,
        kernel_data_V_10_19,
        kernel_data_V_10_20,
        kernel_data_V_10_21,
        kernel_data_V_10_22,
        kernel_data_V_10_23,
        kernel_data_V_10_24,
        kernel_data_V_10_25,
        kernel_data_V_10_26,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] kernel_data_V_10_0;
input  [15:0] kernel_data_V_10_1;
input  [15:0] kernel_data_V_10_2;
input  [15:0] kernel_data_V_10_3;
input  [15:0] kernel_data_V_10_4;
input  [15:0] kernel_data_V_10_5;
input  [15:0] kernel_data_V_10_6;
input  [15:0] kernel_data_V_10_7;
input  [15:0] kernel_data_V_10_8;
input  [15:0] kernel_data_V_10_9;
input  [15:0] kernel_data_V_10_10;
input  [15:0] kernel_data_V_10_11;
input  [15:0] kernel_data_V_10_12;
input  [15:0] kernel_data_V_10_13;
input  [15:0] kernel_data_V_10_14;
input  [15:0] kernel_data_V_10_15;
input  [15:0] kernel_data_V_10_16;
input  [15:0] kernel_data_V_10_17;
input  [15:0] kernel_data_V_10_18;
input  [15:0] kernel_data_V_10_19;
input  [15:0] kernel_data_V_10_20;
input  [15:0] kernel_data_V_10_21;
input  [15:0] kernel_data_V_10_22;
input  [15:0] kernel_data_V_10_23;
input  [15:0] kernel_data_V_10_24;
input  [15:0] kernel_data_V_10_25;
input  [15:0] kernel_data_V_10_26;
output  [37:0] ap_return_0;
output  [37:0] ap_return_1;
output  [37:0] ap_return_2;
output  [37:0] ap_return_3;
output  [37:0] ap_return_4;
output  [37:0] ap_return_5;
output  [37:0] ap_return_6;
output  [37:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[37:0] ap_return_0;
reg[37:0] ap_return_1;
reg[37:0] ap_return_2;
reg[37:0] ap_return_3;
reg[37:0] ap_return_4;
reg[37:0] ap_return_5;
reg[37:0] ap_return_6;
reg[37:0] ap_return_7;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_1060_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] outidx_2_address0;
reg    outidx_2_ce0;
wire   [2:0] outidx_2_q0;
wire   [7:0] w2_V_address0;
reg    w2_V_ce0;
wire   [15:0] w2_V_q0;
reg   [31:0] in_index34_reg_233;
reg   [7:0] w_index33_reg_247;
reg   [15:0] x_V32_reg_320;
reg   [15:0] x_V_1530_reg_334;
reg   [15:0] x_V_1628_reg_348;
reg   [15:0] x_V_1726_reg_362;
reg   [15:0] x_V_1824_reg_376;
reg   [15:0] x_V_1922_reg_390;
reg   [15:0] x_V_2020_reg_404;
reg   [15:0] x_V_2118_reg_418;
reg   [15:0] acc_V_0_016_reg_432;
reg   [15:0] acc_V_1_015_reg_446;
reg   [15:0] acc_V_2_014_reg_460;
reg   [15:0] acc_V_3_013_reg_474;
reg   [15:0] acc_V_4_012_reg_488;
reg   [15:0] acc_V_5_011_reg_502;
reg   [15:0] acc_V_6_010_reg_516;
reg   [15:0] acc_V_7_09_reg_530;
wire   [7:0] w_index_fu_1024_p2;
reg   [7:0] w_index_reg_1387;
wire   [4:0] empty_338_fu_1036_p1;
reg   [4:0] empty_338_reg_1397;
wire   [31:0] in_index_fu_1052_p3;
reg   [31:0] in_index_reg_1406;
reg   [0:0] icmp_ln135_reg_1411;
reg   [0:0] icmp_ln135_reg_1411_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1411_pp0_iter2_reg;
reg   [2:0] out_index_reg_1415;
reg   [2:0] out_index_reg_1415_pp0_iter2_reg;
reg  signed [15:0] w_V_reg_1555;
reg   [15:0] trunc_ln_reg_1560;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_in_index34_phi_fu_237_p6;
reg   [7:0] ap_phi_mux_w_index33_phi_fu_251_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_a_V_reg_261;
reg   [15:0] ap_phi_reg_pp0_iter1_a_V_reg_261;
reg  signed [15:0] ap_phi_reg_pp0_iter2_a_V_reg_261;
reg   [15:0] ap_phi_mux_x_V_phi_fu_998_p16;
reg   [15:0] ap_phi_mux_x_V_8_phi_fu_968_p16;
reg   [15:0] ap_phi_mux_x_V_9_phi_fu_938_p16;
reg   [15:0] ap_phi_mux_x_V_10_phi_fu_908_p16;
reg   [15:0] ap_phi_mux_x_V_11_phi_fu_878_p16;
reg   [15:0] ap_phi_mux_x_V_12_phi_fu_848_p16;
reg   [15:0] ap_phi_mux_x_V_13_phi_fu_818_p16;
reg   [15:0] ap_phi_mux_x_V_14_phi_fu_788_p16;
reg   [15:0] ap_phi_mux_acc_V_0_1_phi_fu_758_p16;
reg   [15:0] ap_phi_mux_acc_V_1_1_phi_fu_728_p16;
reg   [15:0] ap_phi_mux_acc_V_2_1_phi_fu_698_p16;
reg   [15:0] ap_phi_mux_acc_V_3_1_phi_fu_668_p16;
reg   [15:0] ap_phi_mux_acc_V_4_1_phi_fu_638_p16;
reg   [15:0] ap_phi_mux_acc_V_5_1_phi_fu_608_p16;
reg   [15:0] ap_phi_mux_acc_V_6_1_phi_fu_578_p16;
reg   [15:0] ap_phi_mux_acc_V_7_1_phi_fu_548_p16;
wire   [15:0] acc_V_0_fu_1211_p2;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_7_1_reg_544;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_6_1_reg_574;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_5_1_reg_604;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_4_1_reg_634;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_3_1_reg_664;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_2_1_reg_694;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_1_1_reg_724;
wire   [15:0] ap_phi_reg_pp0_iter3_acc_V_0_1_reg_754;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_14_reg_784;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_13_reg_814;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_12_reg_844;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_11_reg_874;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_10_reg_904;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_9_reg_934;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_8_reg_964;
wire   [15:0] ap_phi_reg_pp0_iter3_x_V_reg_994;
wire   [63:0] zext_ln135_fu_1030_p1;
wire   [31:0] in_index_2_fu_1040_p2;
wire   [0:0] icmp_ln154_fu_1046_p2;
wire  signed [28:0] mul_ln1115_fu_1380_p2;
wire   [15:0] tmp_fu_1190_p10;
wire   [28:0] shl_ln_fu_1232_p3;
wire   [28:0] shl_ln728_8_fu_1244_p3;
wire   [28:0] shl_ln728_9_fu_1256_p3;
wire   [28:0] shl_ln728_s_fu_1268_p3;
wire   [28:0] shl_ln728_1_fu_1280_p3;
wire   [28:0] shl_ln728_2_fu_1292_p3;
wire   [28:0] shl_ln728_3_fu_1304_p3;
wire   [28:0] shl_ln728_4_fu_1316_p3;
wire  signed [37:0] sext_ln110_fu_1240_p1;
wire  signed [37:0] sext_ln110_7_fu_1252_p1;
wire  signed [37:0] sext_ln110_8_fu_1264_p1;
wire  signed [37:0] sext_ln110_9_fu_1276_p1;
wire  signed [37:0] sext_ln110_10_fu_1288_p1;
wire  signed [37:0] sext_ln110_11_fu_1300_p1;
wire  signed [37:0] sext_ln110_12_fu_1312_p1;
wire  signed [37:0] sext_ln166_fu_1324_p1;
reg   [37:0] ap_return_0_preg;
reg   [37:0] ap_return_1_preg;
reg   [37:0] ap_return_2_preg;
reg   [37:0] ap_return_3_preg;
reg   [37:0] ap_return_4_preg;
reg   [37:0] ap_return_5_preg;
reg   [37:0] ap_return_6_preg;
reg   [37:0] ap_return_7_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_364;
reg    ap_condition_334;
reg    ap_condition_358;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_return_0_preg = 38'd0;
#0 ap_return_1_preg = 38'd0;
#0 ap_return_2_preg = 38'd0;
#0 ap_return_3_preg = 38'd0;
#0 ap_return_4_preg = 38'd0;
#0 ap_return_5_preg = 38'd0;
#0 ap_return_6_preg = 38'd0;
#0 ap_return_7_preg = 38'd0;
end

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_ouhbi #(
    .DataWidth( 3 ),
    .AddressRange( 216 ),
    .AddressWidth( 8 ))
outidx_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_2_address0),
    .ce0(outidx_2_ce0),
    .q0(outidx_2_q0)
);

myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s_w2_V #(
    .DataWidth( 16 ),
    .AddressRange( 216 ),
    .AddressWidth( 8 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

myproject_mux_83_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
mux_83_16_1_1_U32(
    .din0(acc_V_0_016_reg_432),
    .din1(acc_V_1_015_reg_446),
    .din2(acc_V_2_014_reg_460),
    .din3(acc_V_3_013_reg_474),
    .din4(acc_V_4_012_reg_488),
    .din5(acc_V_5_011_reg_502),
    .din6(acc_V_6_010_reg_516),
    .din7(acc_V_7_09_reg_530),
    .din8(out_index_reg_1415_pp0_iter2_reg),
    .dout(tmp_fu_1190_p10)
);

myproject_mul_mul_16s_16s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_16s_16s_29_1_1_U33(
    .din0(w_V_reg_1555),
    .din1(ap_phi_reg_pp0_iter2_a_V_reg_261),
    .dout(mul_ln1115_fu_1380_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[13] <= 1'b0;
        ap_return_0_preg[14] <= 1'b0;
        ap_return_0_preg[15] <= 1'b0;
        ap_return_0_preg[16] <= 1'b0;
        ap_return_0_preg[17] <= 1'b0;
        ap_return_0_preg[18] <= 1'b0;
        ap_return_0_preg[19] <= 1'b0;
        ap_return_0_preg[20] <= 1'b0;
        ap_return_0_preg[21] <= 1'b0;
        ap_return_0_preg[22] <= 1'b0;
        ap_return_0_preg[23] <= 1'b0;
        ap_return_0_preg[24] <= 1'b0;
        ap_return_0_preg[25] <= 1'b0;
        ap_return_0_preg[26] <= 1'b0;
        ap_return_0_preg[27] <= 1'b0;
        ap_return_0_preg[28] <= 1'b0;
        ap_return_0_preg[29] <= 1'b0;
        ap_return_0_preg[30] <= 1'b0;
        ap_return_0_preg[31] <= 1'b0;
        ap_return_0_preg[32] <= 1'b0;
        ap_return_0_preg[33] <= 1'b0;
        ap_return_0_preg[34] <= 1'b0;
        ap_return_0_preg[35] <= 1'b0;
        ap_return_0_preg[36] <= 1'b0;
        ap_return_0_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_0_preg[37 : 13] <= sext_ln110_fu_1240_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[13] <= 1'b0;
        ap_return_1_preg[14] <= 1'b0;
        ap_return_1_preg[15] <= 1'b0;
        ap_return_1_preg[16] <= 1'b0;
        ap_return_1_preg[17] <= 1'b0;
        ap_return_1_preg[18] <= 1'b0;
        ap_return_1_preg[19] <= 1'b0;
        ap_return_1_preg[20] <= 1'b0;
        ap_return_1_preg[21] <= 1'b0;
        ap_return_1_preg[22] <= 1'b0;
        ap_return_1_preg[23] <= 1'b0;
        ap_return_1_preg[24] <= 1'b0;
        ap_return_1_preg[25] <= 1'b0;
        ap_return_1_preg[26] <= 1'b0;
        ap_return_1_preg[27] <= 1'b0;
        ap_return_1_preg[28] <= 1'b0;
        ap_return_1_preg[29] <= 1'b0;
        ap_return_1_preg[30] <= 1'b0;
        ap_return_1_preg[31] <= 1'b0;
        ap_return_1_preg[32] <= 1'b0;
        ap_return_1_preg[33] <= 1'b0;
        ap_return_1_preg[34] <= 1'b0;
        ap_return_1_preg[35] <= 1'b0;
        ap_return_1_preg[36] <= 1'b0;
        ap_return_1_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_1_preg[37 : 13] <= sext_ln110_7_fu_1252_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[13] <= 1'b0;
        ap_return_2_preg[14] <= 1'b0;
        ap_return_2_preg[15] <= 1'b0;
        ap_return_2_preg[16] <= 1'b0;
        ap_return_2_preg[17] <= 1'b0;
        ap_return_2_preg[18] <= 1'b0;
        ap_return_2_preg[19] <= 1'b0;
        ap_return_2_preg[20] <= 1'b0;
        ap_return_2_preg[21] <= 1'b0;
        ap_return_2_preg[22] <= 1'b0;
        ap_return_2_preg[23] <= 1'b0;
        ap_return_2_preg[24] <= 1'b0;
        ap_return_2_preg[25] <= 1'b0;
        ap_return_2_preg[26] <= 1'b0;
        ap_return_2_preg[27] <= 1'b0;
        ap_return_2_preg[28] <= 1'b0;
        ap_return_2_preg[29] <= 1'b0;
        ap_return_2_preg[30] <= 1'b0;
        ap_return_2_preg[31] <= 1'b0;
        ap_return_2_preg[32] <= 1'b0;
        ap_return_2_preg[33] <= 1'b0;
        ap_return_2_preg[34] <= 1'b0;
        ap_return_2_preg[35] <= 1'b0;
        ap_return_2_preg[36] <= 1'b0;
        ap_return_2_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_2_preg[37 : 13] <= sext_ln110_8_fu_1264_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[13] <= 1'b0;
        ap_return_3_preg[14] <= 1'b0;
        ap_return_3_preg[15] <= 1'b0;
        ap_return_3_preg[16] <= 1'b0;
        ap_return_3_preg[17] <= 1'b0;
        ap_return_3_preg[18] <= 1'b0;
        ap_return_3_preg[19] <= 1'b0;
        ap_return_3_preg[20] <= 1'b0;
        ap_return_3_preg[21] <= 1'b0;
        ap_return_3_preg[22] <= 1'b0;
        ap_return_3_preg[23] <= 1'b0;
        ap_return_3_preg[24] <= 1'b0;
        ap_return_3_preg[25] <= 1'b0;
        ap_return_3_preg[26] <= 1'b0;
        ap_return_3_preg[27] <= 1'b0;
        ap_return_3_preg[28] <= 1'b0;
        ap_return_3_preg[29] <= 1'b0;
        ap_return_3_preg[30] <= 1'b0;
        ap_return_3_preg[31] <= 1'b0;
        ap_return_3_preg[32] <= 1'b0;
        ap_return_3_preg[33] <= 1'b0;
        ap_return_3_preg[34] <= 1'b0;
        ap_return_3_preg[35] <= 1'b0;
        ap_return_3_preg[36] <= 1'b0;
        ap_return_3_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_3_preg[37 : 13] <= sext_ln110_9_fu_1276_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_4_preg[13] <= 1'b0;
        ap_return_4_preg[14] <= 1'b0;
        ap_return_4_preg[15] <= 1'b0;
        ap_return_4_preg[16] <= 1'b0;
        ap_return_4_preg[17] <= 1'b0;
        ap_return_4_preg[18] <= 1'b0;
        ap_return_4_preg[19] <= 1'b0;
        ap_return_4_preg[20] <= 1'b0;
        ap_return_4_preg[21] <= 1'b0;
        ap_return_4_preg[22] <= 1'b0;
        ap_return_4_preg[23] <= 1'b0;
        ap_return_4_preg[24] <= 1'b0;
        ap_return_4_preg[25] <= 1'b0;
        ap_return_4_preg[26] <= 1'b0;
        ap_return_4_preg[27] <= 1'b0;
        ap_return_4_preg[28] <= 1'b0;
        ap_return_4_preg[29] <= 1'b0;
        ap_return_4_preg[30] <= 1'b0;
        ap_return_4_preg[31] <= 1'b0;
        ap_return_4_preg[32] <= 1'b0;
        ap_return_4_preg[33] <= 1'b0;
        ap_return_4_preg[34] <= 1'b0;
        ap_return_4_preg[35] <= 1'b0;
        ap_return_4_preg[36] <= 1'b0;
        ap_return_4_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_4_preg[37 : 13] <= sext_ln110_10_fu_1288_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_5_preg[13] <= 1'b0;
        ap_return_5_preg[14] <= 1'b0;
        ap_return_5_preg[15] <= 1'b0;
        ap_return_5_preg[16] <= 1'b0;
        ap_return_5_preg[17] <= 1'b0;
        ap_return_5_preg[18] <= 1'b0;
        ap_return_5_preg[19] <= 1'b0;
        ap_return_5_preg[20] <= 1'b0;
        ap_return_5_preg[21] <= 1'b0;
        ap_return_5_preg[22] <= 1'b0;
        ap_return_5_preg[23] <= 1'b0;
        ap_return_5_preg[24] <= 1'b0;
        ap_return_5_preg[25] <= 1'b0;
        ap_return_5_preg[26] <= 1'b0;
        ap_return_5_preg[27] <= 1'b0;
        ap_return_5_preg[28] <= 1'b0;
        ap_return_5_preg[29] <= 1'b0;
        ap_return_5_preg[30] <= 1'b0;
        ap_return_5_preg[31] <= 1'b0;
        ap_return_5_preg[32] <= 1'b0;
        ap_return_5_preg[33] <= 1'b0;
        ap_return_5_preg[34] <= 1'b0;
        ap_return_5_preg[35] <= 1'b0;
        ap_return_5_preg[36] <= 1'b0;
        ap_return_5_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_5_preg[37 : 13] <= sext_ln110_11_fu_1300_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_6_preg[13] <= 1'b0;
        ap_return_6_preg[14] <= 1'b0;
        ap_return_6_preg[15] <= 1'b0;
        ap_return_6_preg[16] <= 1'b0;
        ap_return_6_preg[17] <= 1'b0;
        ap_return_6_preg[18] <= 1'b0;
        ap_return_6_preg[19] <= 1'b0;
        ap_return_6_preg[20] <= 1'b0;
        ap_return_6_preg[21] <= 1'b0;
        ap_return_6_preg[22] <= 1'b0;
        ap_return_6_preg[23] <= 1'b0;
        ap_return_6_preg[24] <= 1'b0;
        ap_return_6_preg[25] <= 1'b0;
        ap_return_6_preg[26] <= 1'b0;
        ap_return_6_preg[27] <= 1'b0;
        ap_return_6_preg[28] <= 1'b0;
        ap_return_6_preg[29] <= 1'b0;
        ap_return_6_preg[30] <= 1'b0;
        ap_return_6_preg[31] <= 1'b0;
        ap_return_6_preg[32] <= 1'b0;
        ap_return_6_preg[33] <= 1'b0;
        ap_return_6_preg[34] <= 1'b0;
        ap_return_6_preg[35] <= 1'b0;
        ap_return_6_preg[36] <= 1'b0;
        ap_return_6_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_6_preg[37 : 13] <= sext_ln110_12_fu_1312_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_7_preg[13] <= 1'b0;
        ap_return_7_preg[14] <= 1'b0;
        ap_return_7_preg[15] <= 1'b0;
        ap_return_7_preg[16] <= 1'b0;
        ap_return_7_preg[17] <= 1'b0;
        ap_return_7_preg[18] <= 1'b0;
        ap_return_7_preg[19] <= 1'b0;
        ap_return_7_preg[20] <= 1'b0;
        ap_return_7_preg[21] <= 1'b0;
        ap_return_7_preg[22] <= 1'b0;
        ap_return_7_preg[23] <= 1'b0;
        ap_return_7_preg[24] <= 1'b0;
        ap_return_7_preg[25] <= 1'b0;
        ap_return_7_preg[26] <= 1'b0;
        ap_return_7_preg[27] <= 1'b0;
        ap_return_7_preg[28] <= 1'b0;
        ap_return_7_preg[29] <= 1'b0;
        ap_return_7_preg[30] <= 1'b0;
        ap_return_7_preg[31] <= 1'b0;
        ap_return_7_preg[32] <= 1'b0;
        ap_return_7_preg[33] <= 1'b0;
        ap_return_7_preg[34] <= 1'b0;
        ap_return_7_preg[35] <= 1'b0;
        ap_return_7_preg[36] <= 1'b0;
        ap_return_7_preg[37] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
                        ap_return_7_preg[37 : 13] <= sext_ln166_fu_1324_p1[37 : 13];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_0_016_reg_432 <= ap_phi_mux_acc_V_0_1_phi_fu_758_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_0_016_reg_432 <= 16'd45722;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_1_015_reg_446 <= ap_phi_mux_acc_V_1_1_phi_fu_728_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1_015_reg_446 <= 16'd16298;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_2_014_reg_460 <= ap_phi_mux_acc_V_2_1_phi_fu_698_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_2_014_reg_460 <= 16'd13699;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_3_013_reg_474 <= ap_phi_mux_acc_V_3_1_phi_fu_668_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_3_013_reg_474 <= 16'd18546;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_4_012_reg_488 <= ap_phi_mux_acc_V_4_1_phi_fu_638_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_4_012_reg_488 <= 16'd7844;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_5_011_reg_502 <= ap_phi_mux_acc_V_5_1_phi_fu_608_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_5_011_reg_502 <= 16'd45429;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_6_010_reg_516 <= ap_phi_mux_acc_V_6_1_phi_fu_578_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_6_010_reg_516 <= 16'd7249;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        acc_V_7_09_reg_530 <= ap_phi_mux_acc_V_7_1_phi_fu_548_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_7_09_reg_530 <= 16'd12473;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if ((1'b1 == ap_condition_334)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_26;
        end else if ((empty_338_reg_1397 == 5'd25)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_25;
        end else if ((empty_338_reg_1397 == 5'd24)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_24;
        end else if ((empty_338_reg_1397 == 5'd23)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_23;
        end else if ((empty_338_reg_1397 == 5'd22)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_22;
        end else if ((empty_338_reg_1397 == 5'd21)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_21;
        end else if ((empty_338_reg_1397 == 5'd20)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_20;
        end else if ((empty_338_reg_1397 == 5'd19)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_19;
        end else if ((empty_338_reg_1397 == 5'd18)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_18;
        end else if ((empty_338_reg_1397 == 5'd17)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_17;
        end else if ((empty_338_reg_1397 == 5'd16)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_16;
        end else if ((empty_338_reg_1397 == 5'd15)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_15;
        end else if ((empty_338_reg_1397 == 5'd14)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_14;
        end else if ((empty_338_reg_1397 == 5'd13)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_13;
        end else if ((empty_338_reg_1397 == 5'd12)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_12;
        end else if ((empty_338_reg_1397 == 5'd11)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_11;
        end else if ((empty_338_reg_1397 == 5'd10)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_10;
        end else if ((empty_338_reg_1397 == 5'd9)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_9;
        end else if ((empty_338_reg_1397 == 5'd8)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_8;
        end else if ((empty_338_reg_1397 == 5'd7)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_7;
        end else if ((empty_338_reg_1397 == 5'd6)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_6;
        end else if ((empty_338_reg_1397 == 5'd5)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_5;
        end else if ((empty_338_reg_1397 == 5'd4)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_4;
        end else if ((empty_338_reg_1397 == 5'd3)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_3;
        end else if ((empty_338_reg_1397 == 5'd2)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_2;
        end else if ((empty_338_reg_1397 == 5'd1)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_1;
        end else if ((empty_338_reg_1397 == 5'd0)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= kernel_data_V_10_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_a_V_reg_261 <= ap_phi_reg_pp0_iter1_a_V_reg_261;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1411 == 1'd0))) begin
        in_index34_reg_233 <= in_index_reg_1406;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1411 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index34_reg_233 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1411 == 1'd0))) begin
        w_index33_reg_247 <= w_index_reg_1387;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln135_reg_1411 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index33_reg_247 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V32_reg_320 <= ap_phi_mux_x_V_phi_fu_998_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V32_reg_320 <= 16'd45722;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_1530_reg_334 <= ap_phi_mux_x_V_8_phi_fu_968_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_1530_reg_334 <= 16'd16298;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_1628_reg_348 <= ap_phi_mux_x_V_9_phi_fu_938_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_1628_reg_348 <= 16'd13699;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_1726_reg_362 <= ap_phi_mux_x_V_10_phi_fu_908_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_1726_reg_362 <= 16'd18546;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_1824_reg_376 <= ap_phi_mux_x_V_11_phi_fu_878_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_1824_reg_376 <= 16'd7844;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_1922_reg_390 <= ap_phi_mux_x_V_12_phi_fu_848_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_1922_reg_390 <= 16'd45429;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_2020_reg_404 <= ap_phi_mux_x_V_13_phi_fu_818_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_2020_reg_404 <= 16'd7249;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd0))) begin
        x_V_2118_reg_418 <= ap_phi_mux_x_V_14_phi_fu_788_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_V_2118_reg_418 <= 16'd12473;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_a_V_reg_261 <= ap_phi_reg_pp0_iter0_a_V_reg_261;
        in_index_reg_1406 <= in_index_fu_1052_p3;
        w_index_reg_1387 <= w_index_fu_1024_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_338_reg_1397 <= empty_338_fu_1036_p1;
        icmp_ln135_reg_1411 <= icmp_ln135_fu_1060_p2;
        icmp_ln135_reg_1411_pp0_iter1_reg <= icmp_ln135_reg_1411;
        out_index_reg_1415 <= outidx_2_q0;
        w_V_reg_1555 <= w2_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln135_reg_1411_pp0_iter2_reg <= icmp_ln135_reg_1411_pp0_iter1_reg;
        out_index_reg_1415_pp0_iter2_reg <= out_index_reg_1415;
        trunc_ln_reg_1560 <= {{mul_ln1115_fu_1380_p2[28:13]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_acc_V_0_1_phi_fu_758_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_0_1_phi_fu_758_p16 = acc_V_0_016_reg_432;
    end else begin
        ap_phi_mux_acc_V_0_1_phi_fu_758_p16 = ap_phi_reg_pp0_iter3_acc_V_0_1_reg_754;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_acc_V_1_1_phi_fu_728_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_1_1_phi_fu_728_p16 = acc_V_1_015_reg_446;
    end else begin
        ap_phi_mux_acc_V_1_1_phi_fu_728_p16 = ap_phi_reg_pp0_iter3_acc_V_1_1_reg_724;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_acc_V_2_1_phi_fu_698_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_2_1_phi_fu_698_p16 = acc_V_2_014_reg_460;
    end else begin
        ap_phi_mux_acc_V_2_1_phi_fu_698_p16 = ap_phi_reg_pp0_iter3_acc_V_2_1_reg_694;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_acc_V_3_1_phi_fu_668_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_3_1_phi_fu_668_p16 = acc_V_3_013_reg_474;
    end else begin
        ap_phi_mux_acc_V_3_1_phi_fu_668_p16 = ap_phi_reg_pp0_iter3_acc_V_3_1_reg_664;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_acc_V_4_1_phi_fu_638_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_4_1_phi_fu_638_p16 = acc_V_4_012_reg_488;
    end else begin
        ap_phi_mux_acc_V_4_1_phi_fu_638_p16 = ap_phi_reg_pp0_iter3_acc_V_4_1_reg_634;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_acc_V_5_1_phi_fu_608_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_5_1_phi_fu_608_p16 = acc_V_5_011_reg_502;
    end else begin
        ap_phi_mux_acc_V_5_1_phi_fu_608_p16 = ap_phi_reg_pp0_iter3_acc_V_5_1_reg_604;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_acc_V_6_1_phi_fu_578_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_6_1_phi_fu_578_p16 = acc_V_6_010_reg_516;
    end else begin
        ap_phi_mux_acc_V_6_1_phi_fu_578_p16 = ap_phi_reg_pp0_iter3_acc_V_6_1_reg_574;
    end
end

always @ (*) begin
    if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_acc_V_7_1_phi_fu_548_p16 = acc_V_7_09_reg_530;
    end else if ((out_index_reg_1415_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_acc_V_7_1_phi_fu_548_p16 = acc_V_0_fu_1211_p2;
    end else begin
        ap_phi_mux_acc_V_7_1_phi_fu_548_p16 = ap_phi_reg_pp0_iter3_acc_V_7_1_reg_544;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_364)) begin
        if ((icmp_ln135_reg_1411 == 1'd1)) begin
            ap_phi_mux_in_index34_phi_fu_237_p6 = 32'd0;
        end else if ((icmp_ln135_reg_1411 == 1'd0)) begin
            ap_phi_mux_in_index34_phi_fu_237_p6 = in_index_reg_1406;
        end else begin
            ap_phi_mux_in_index34_phi_fu_237_p6 = in_index34_reg_233;
        end
    end else begin
        ap_phi_mux_in_index34_phi_fu_237_p6 = in_index34_reg_233;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_364)) begin
        if ((icmp_ln135_reg_1411 == 1'd1)) begin
            ap_phi_mux_w_index33_phi_fu_251_p6 = 8'd0;
        end else if ((icmp_ln135_reg_1411 == 1'd0)) begin
            ap_phi_mux_w_index33_phi_fu_251_p6 = w_index_reg_1387;
        end else begin
            ap_phi_mux_w_index33_phi_fu_251_p6 = w_index33_reg_247;
        end
    end else begin
        ap_phi_mux_w_index33_phi_fu_251_p6 = w_index33_reg_247;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_x_V_10_phi_fu_908_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_10_phi_fu_908_p16 = x_V_1726_reg_362;
    end else begin
        ap_phi_mux_x_V_10_phi_fu_908_p16 = ap_phi_reg_pp0_iter3_x_V_10_reg_904;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_x_V_11_phi_fu_878_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_11_phi_fu_878_p16 = x_V_1824_reg_376;
    end else begin
        ap_phi_mux_x_V_11_phi_fu_878_p16 = ap_phi_reg_pp0_iter3_x_V_11_reg_874;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_x_V_12_phi_fu_848_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_12_phi_fu_848_p16 = x_V_1922_reg_390;
    end else begin
        ap_phi_mux_x_V_12_phi_fu_848_p16 = ap_phi_reg_pp0_iter3_x_V_12_reg_844;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_x_V_13_phi_fu_818_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_13_phi_fu_818_p16 = x_V_2020_reg_404;
    end else begin
        ap_phi_mux_x_V_13_phi_fu_818_p16 = ap_phi_reg_pp0_iter3_x_V_13_reg_814;
    end
end

always @ (*) begin
    if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_x_V_14_phi_fu_788_p16 = x_V_2118_reg_418;
    end else if ((out_index_reg_1415_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_x_V_14_phi_fu_788_p16 = acc_V_0_fu_1211_p2;
    end else begin
        ap_phi_mux_x_V_14_phi_fu_788_p16 = ap_phi_reg_pp0_iter3_x_V_14_reg_784;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_x_V_8_phi_fu_968_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_8_phi_fu_968_p16 = x_V_1530_reg_334;
    end else begin
        ap_phi_mux_x_V_8_phi_fu_968_p16 = ap_phi_reg_pp0_iter3_x_V_8_reg_964;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_x_V_9_phi_fu_938_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd0) | (out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_9_phi_fu_938_p16 = x_V_1628_reg_348;
    end else begin
        ap_phi_mux_x_V_9_phi_fu_938_p16 = ap_phi_reg_pp0_iter3_x_V_9_reg_934;
    end
end

always @ (*) begin
    if ((out_index_reg_1415_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_x_V_phi_fu_998_p16 = acc_V_0_fu_1211_p2;
    end else if (((out_index_reg_1415_pp0_iter2_reg == 3'd1) | (out_index_reg_1415_pp0_iter2_reg == 3'd2) | (out_index_reg_1415_pp0_iter2_reg == 3'd3) | (out_index_reg_1415_pp0_iter2_reg == 3'd4) | (out_index_reg_1415_pp0_iter2_reg == 3'd5) | (out_index_reg_1415_pp0_iter2_reg == 3'd6) | (out_index_reg_1415_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_x_V_phi_fu_998_p16 = x_V32_reg_320;
    end else begin
        ap_phi_mux_x_V_phi_fu_998_p16 = ap_phi_reg_pp0_iter3_x_V_reg_994;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln135_fu_1060_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_0 = sext_ln110_fu_1240_p1;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_1 = sext_ln110_7_fu_1252_p1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_2 = sext_ln110_8_fu_1264_p1;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_3 = sext_ln110_9_fu_1276_p1;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_4 = sext_ln110_10_fu_1288_p1;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_5 = sext_ln110_11_fu_1300_p1;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_6 = sext_ln110_12_fu_1312_p1;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln135_reg_1411_pp0_iter2_reg == 1'd1))) begin
        ap_return_7 = sext_ln166_fu_1324_p1;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_2_ce0 = 1'b1;
    end else begin
        outidx_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_0_fu_1211_p2 = (trunc_ln_reg_1560 + tmp_fu_1190_p10);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_334 = ((empty_338_reg_1397 == 5'd26) | ((empty_338_reg_1397 == 5'd27) | ((empty_338_reg_1397 == 5'd28) | ((empty_338_reg_1397 == 5'd29) | ((empty_338_reg_1397 == 5'd30) | (empty_338_reg_1397 == 5'd31))))));
end

always @ (*) begin
    ap_condition_358 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_364 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_a_V_reg_261 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_0_1_reg_754 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_1_1_reg_724 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_2_1_reg_694 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_3_1_reg_664 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_4_1_reg_634 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_5_1_reg_604 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_6_1_reg_574 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_7_1_reg_544 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_10_reg_904 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_11_reg_874 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_12_reg_844 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_13_reg_814 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_14_reg_784 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_8_reg_964 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_9_reg_934 = 'bx;

assign ap_phi_reg_pp0_iter3_x_V_reg_994 = 'bx;

assign empty_338_fu_1036_p1 = ap_phi_mux_in_index34_phi_fu_237_p6[4:0];

assign icmp_ln135_fu_1060_p2 = ((ap_phi_mux_w_index33_phi_fu_251_p6 == 8'd215) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_1046_p2 = (($signed(in_index_2_fu_1040_p2) > $signed(32'd26)) ? 1'b1 : 1'b0);

assign in_index_2_fu_1040_p2 = (ap_phi_mux_in_index34_phi_fu_237_p6 + 32'd1);

assign in_index_fu_1052_p3 = ((icmp_ln154_fu_1046_p2[0:0] == 1'b1) ? 32'd0 : in_index_2_fu_1040_p2);

assign outidx_2_address0 = zext_ln135_fu_1030_p1;

assign sext_ln110_10_fu_1288_p1 = $signed(shl_ln728_1_fu_1280_p3);

assign sext_ln110_11_fu_1300_p1 = $signed(shl_ln728_2_fu_1292_p3);

assign sext_ln110_12_fu_1312_p1 = $signed(shl_ln728_3_fu_1304_p3);

assign sext_ln110_7_fu_1252_p1 = $signed(shl_ln728_8_fu_1244_p3);

assign sext_ln110_8_fu_1264_p1 = $signed(shl_ln728_9_fu_1256_p3);

assign sext_ln110_9_fu_1276_p1 = $signed(shl_ln728_s_fu_1268_p3);

assign sext_ln110_fu_1240_p1 = $signed(shl_ln_fu_1232_p3);

assign sext_ln166_fu_1324_p1 = $signed(shl_ln728_4_fu_1316_p3);

assign shl_ln728_1_fu_1280_p3 = {{ap_phi_mux_x_V_11_phi_fu_878_p16}, {13'd0}};

assign shl_ln728_2_fu_1292_p3 = {{ap_phi_mux_x_V_12_phi_fu_848_p16}, {13'd0}};

assign shl_ln728_3_fu_1304_p3 = {{ap_phi_mux_x_V_13_phi_fu_818_p16}, {13'd0}};

assign shl_ln728_4_fu_1316_p3 = {{ap_phi_mux_x_V_14_phi_fu_788_p16}, {13'd0}};

assign shl_ln728_8_fu_1244_p3 = {{ap_phi_mux_x_V_8_phi_fu_968_p16}, {13'd0}};

assign shl_ln728_9_fu_1256_p3 = {{ap_phi_mux_x_V_9_phi_fu_938_p16}, {13'd0}};

assign shl_ln728_s_fu_1268_p3 = {{ap_phi_mux_x_V_10_phi_fu_908_p16}, {13'd0}};

assign shl_ln_fu_1232_p3 = {{ap_phi_mux_x_V_phi_fu_998_p16}, {13'd0}};

assign w2_V_address0 = zext_ln135_fu_1030_p1;

assign w_index_fu_1024_p2 = (ap_phi_mux_w_index33_phi_fu_251_p6 + 8'd1);

assign zext_ln135_fu_1030_p1 = ap_phi_mux_w_index33_phi_fu_251_p6;

always @ (posedge ap_clk) begin
    ap_return_0_preg[12:0] <= 13'b0000000000000;
    ap_return_1_preg[12:0] <= 13'b0000000000000;
    ap_return_2_preg[12:0] <= 13'b0000000000000;
    ap_return_3_preg[12:0] <= 13'b0000000000000;
    ap_return_4_preg[12:0] <= 13'b0000000000000;
    ap_return_5_preg[12:0] <= 13'b0000000000000;
    ap_return_6_preg[12:0] <= 13'b0000000000000;
    ap_return_7_preg[12:0] <= 13'b0000000000000;
end

endmodule //myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_38_12_5_3_0_config2_mult_s
