// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_array_ap_fixed_42_16_5_3_0_32u_config18_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer17_out_dout,
        layer17_out_empty_n,
        layer17_out_read,
        layer18_out_din,
        layer18_out_full_n,
        layer18_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] layer17_out_dout;
input   layer17_out_empty_n;
output   layer17_out_read;
output  [2047:0] layer18_out_din;
input   layer18_out_full_n;
output   layer18_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer17_out_read;
reg layer18_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer17_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_1647_p2;
wire   [11:0] add_ln51_fu_1641_p2;
reg   [11:0] add_ln51_reg_1999;
reg    ap_block_state2;
wire   [15:0] trunc_ln145_fu_1653_p1;
reg   [15:0] trunc_ln145_reg_2007;
reg   [15:0] trunc_ln145_s_reg_2012;
reg   [15:0] trunc_ln145_147_reg_2017;
reg   [15:0] trunc_ln145_148_reg_2022;
reg   [15:0] trunc_ln145_149_reg_2027;
reg   [15:0] trunc_ln145_150_reg_2032;
reg   [15:0] trunc_ln145_151_reg_2037;
reg   [15:0] trunc_ln145_152_reg_2042;
reg   [15:0] trunc_ln145_153_reg_2047;
reg   [15:0] trunc_ln145_154_reg_2052;
reg   [15:0] trunc_ln145_155_reg_2057;
reg   [15:0] trunc_ln145_156_reg_2062;
reg   [15:0] trunc_ln145_157_reg_2067;
reg   [15:0] trunc_ln145_158_reg_2072;
reg   [15:0] trunc_ln145_159_reg_2077;
reg   [15:0] trunc_ln145_160_reg_2082;
reg   [15:0] trunc_ln145_161_reg_2087;
reg   [15:0] trunc_ln145_162_reg_2092;
reg   [15:0] trunc_ln145_163_reg_2097;
reg   [15:0] trunc_ln145_164_reg_2102;
reg   [15:0] trunc_ln145_165_reg_2107;
reg   [15:0] trunc_ln145_166_reg_2112;
reg   [15:0] trunc_ln145_167_reg_2117;
reg   [15:0] trunc_ln145_168_reg_2122;
reg   [15:0] trunc_ln145_169_reg_2127;
reg   [15:0] trunc_ln145_170_reg_2132;
reg   [15:0] trunc_ln145_171_reg_2137;
reg   [15:0] trunc_ln145_172_reg_2142;
reg   [15:0] trunc_ln145_173_reg_2147;
reg   [15:0] trunc_ln145_174_reg_2152;
reg   [15:0] trunc_ln145_175_reg_2157;
reg   [15:0] trunc_ln145_176_reg_2162;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready;
wire   [2047:0] grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write;
reg   [11:0] indvar_flatten_reg_878;
reg    ap_block_state1;
wire    ap_CS_fsm_state3;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg;
reg    ap_block_state2_ignore_call36;
reg   [2:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready),
    .layer18_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din),
    .layer18_out_full_n(layer18_out_full_n),
    .layer18_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write),
    .p_read(trunc_ln145_reg_2007),
    .p_read1(trunc_ln145_s_reg_2012),
    .p_read2(trunc_ln145_147_reg_2017),
    .p_read3(trunc_ln145_148_reg_2022),
    .p_read4(trunc_ln145_149_reg_2027),
    .p_read5(trunc_ln145_150_reg_2032),
    .p_read6(trunc_ln145_151_reg_2037),
    .p_read7(trunc_ln145_152_reg_2042),
    .p_read8(trunc_ln145_153_reg_2047),
    .p_read9(trunc_ln145_154_reg_2052),
    .p_read10(trunc_ln145_155_reg_2057),
    .p_read11(trunc_ln145_156_reg_2062),
    .p_read12(trunc_ln145_157_reg_2067),
    .p_read13(trunc_ln145_158_reg_2072),
    .p_read14(trunc_ln145_159_reg_2077),
    .p_read15(trunc_ln145_160_reg_2082),
    .p_read16(trunc_ln145_161_reg_2087),
    .p_read17(trunc_ln145_162_reg_2092),
    .p_read18(trunc_ln145_163_reg_2097),
    .p_read19(trunc_ln145_164_reg_2102),
    .p_read20(trunc_ln145_165_reg_2107),
    .p_read21(trunc_ln145_166_reg_2112),
    .p_read22(trunc_ln145_167_reg_2117),
    .p_read23(trunc_ln145_168_reg_2122),
    .p_read24(trunc_ln145_169_reg_2127),
    .p_read25(trunc_ln145_170_reg_2132),
    .p_read26(trunc_ln145_171_reg_2137),
    .p_read27(trunc_ln145_172_reg_2142),
    .p_read28(trunc_ln145_173_reg_2147),
    .p_read29(trunc_ln145_174_reg_2152),
    .p_read30(trunc_ln145_175_reg_2157),
    .p_read31(trunc_ln145_176_reg_2162)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done == 1'b1))) begin
        indvar_flatten_reg_878 <= add_ln51_reg_1999;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_878 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln51_reg_1999 <= add_ln51_fu_1641_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_1647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln145_147_reg_2017 <= {{layer17_out_dout[47:32]}};
        trunc_ln145_148_reg_2022 <= {{layer17_out_dout[63:48]}};
        trunc_ln145_149_reg_2027 <= {{layer17_out_dout[79:64]}};
        trunc_ln145_150_reg_2032 <= {{layer17_out_dout[95:80]}};
        trunc_ln145_151_reg_2037 <= {{layer17_out_dout[111:96]}};
        trunc_ln145_152_reg_2042 <= {{layer17_out_dout[127:112]}};
        trunc_ln145_153_reg_2047 <= {{layer17_out_dout[143:128]}};
        trunc_ln145_154_reg_2052 <= {{layer17_out_dout[159:144]}};
        trunc_ln145_155_reg_2057 <= {{layer17_out_dout[175:160]}};
        trunc_ln145_156_reg_2062 <= {{layer17_out_dout[191:176]}};
        trunc_ln145_157_reg_2067 <= {{layer17_out_dout[207:192]}};
        trunc_ln145_158_reg_2072 <= {{layer17_out_dout[223:208]}};
        trunc_ln145_159_reg_2077 <= {{layer17_out_dout[239:224]}};
        trunc_ln145_160_reg_2082 <= {{layer17_out_dout[255:240]}};
        trunc_ln145_161_reg_2087 <= {{layer17_out_dout[271:256]}};
        trunc_ln145_162_reg_2092 <= {{layer17_out_dout[287:272]}};
        trunc_ln145_163_reg_2097 <= {{layer17_out_dout[303:288]}};
        trunc_ln145_164_reg_2102 <= {{layer17_out_dout[319:304]}};
        trunc_ln145_165_reg_2107 <= {{layer17_out_dout[335:320]}};
        trunc_ln145_166_reg_2112 <= {{layer17_out_dout[351:336]}};
        trunc_ln145_167_reg_2117 <= {{layer17_out_dout[367:352]}};
        trunc_ln145_168_reg_2122 <= {{layer17_out_dout[383:368]}};
        trunc_ln145_169_reg_2127 <= {{layer17_out_dout[399:384]}};
        trunc_ln145_170_reg_2132 <= {{layer17_out_dout[415:400]}};
        trunc_ln145_171_reg_2137 <= {{layer17_out_dout[431:416]}};
        trunc_ln145_172_reg_2142 <= {{layer17_out_dout[447:432]}};
        trunc_ln145_173_reg_2147 <= {{layer17_out_dout[463:448]}};
        trunc_ln145_174_reg_2152 <= {{layer17_out_dout[479:464]}};
        trunc_ln145_175_reg_2157 <= {{layer17_out_dout[495:480]}};
        trunc_ln145_176_reg_2162 <= {{layer17_out_dout[511:496]}};
        trunc_ln145_reg_2007 <= trunc_ln145_fu_1653_p1;
        trunc_ln145_s_reg_2012 <= {{layer17_out_dout[31:16]}};
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_1647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer17_out_blk_n = layer17_out_empty_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer17_out_read = 1'b1;
    end else begin
        layer17_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer18_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_write;
    end else begin
        layer18_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0)) & (icmp_ln51_fu_1647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_1641_p2 = (indvar_flatten_reg_878 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call36 = ((icmp_ln51_fu_1647_p2 == 1'd0) & (layer17_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_ap_start_reg;

assign icmp_ln51_fu_1647_p2 = ((indvar_flatten_reg_878 == 12'd3136) ? 1'b1 : 1'b0);

assign layer18_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_42_16_5_3_0_32u_config18_s_fu_889_layer18_out_din;

assign start_out = real_start;

assign trunc_ln145_fu_1653_p1 = layer17_out_dout[15:0];

endmodule //myproject_conv_2d_cl_array_array_ap_fixed_42_16_5_3_0_32u_config18_s
