// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_array_ap_fixed_41_15_5_3_0_32u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer9_out_dout,
        layer9_out_empty_n,
        layer9_out_read,
        layer10_out_din,
        layer10_out_full_n,
        layer10_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [255:0] layer9_out_dout;
input   layer9_out_empty_n;
output   layer9_out_read;
output  [2047:0] layer10_out_din;
input   layer10_out_full_n;
output   layer10_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer9_out_read;
reg layer10_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer9_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_863_p2;
wire   [11:0] add_ln51_fu_857_p2;
reg   [11:0] add_ln51_reg_1039;
reg    ap_block_state2;
wire   [15:0] trunc_ln145_fu_869_p1;
reg   [15:0] trunc_ln145_reg_1047;
reg   [15:0] trunc_ln145_s_reg_1052;
reg   [15:0] trunc_ln145_207_reg_1057;
reg   [15:0] trunc_ln145_208_reg_1062;
reg   [15:0] trunc_ln145_209_reg_1067;
reg   [15:0] trunc_ln145_210_reg_1072;
reg   [15:0] trunc_ln145_211_reg_1077;
reg   [15:0] trunc_ln145_212_reg_1082;
reg   [15:0] trunc_ln145_213_reg_1087;
reg   [15:0] trunc_ln145_214_reg_1092;
reg   [15:0] trunc_ln145_215_reg_1097;
reg   [15:0] trunc_ln145_216_reg_1102;
reg   [15:0] trunc_ln145_217_reg_1107;
reg   [15:0] trunc_ln145_218_reg_1112;
reg   [15:0] trunc_ln145_219_reg_1117;
reg   [15:0] trunc_ln145_220_reg_1122;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_ready;
wire   [2047:0] grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_write;
reg   [11:0] indvar_flatten_reg_462;
reg    ap_block_state1;
wire    ap_CS_fsm_state3;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg;
reg    ap_block_state2_ignore_call20;
reg   [2:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_ready),
    .layer10_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_din),
    .layer10_out_full_n(layer10_out_full_n),
    .layer10_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_write),
    .p_read(trunc_ln145_reg_1047),
    .p_read1(trunc_ln145_s_reg_1052),
    .p_read2(trunc_ln145_207_reg_1057),
    .p_read3(trunc_ln145_208_reg_1062),
    .p_read4(trunc_ln145_209_reg_1067),
    .p_read5(trunc_ln145_210_reg_1072),
    .p_read6(trunc_ln145_211_reg_1077),
    .p_read7(trunc_ln145_212_reg_1082),
    .p_read8(trunc_ln145_213_reg_1087),
    .p_read9(trunc_ln145_214_reg_1092),
    .p_read10(trunc_ln145_215_reg_1097),
    .p_read11(trunc_ln145_216_reg_1102),
    .p_read12(trunc_ln145_217_reg_1107),
    .p_read13(trunc_ln145_218_reg_1112),
    .p_read14(trunc_ln145_219_reg_1117),
    .p_read15(trunc_ln145_220_reg_1122)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten_reg_462 <= add_ln51_reg_1039;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_462 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln51_reg_1039 <= add_ln51_fu_857_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_863_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln145_207_reg_1057 <= {{layer9_out_dout[47:32]}};
        trunc_ln145_208_reg_1062 <= {{layer9_out_dout[63:48]}};
        trunc_ln145_209_reg_1067 <= {{layer9_out_dout[79:64]}};
        trunc_ln145_210_reg_1072 <= {{layer9_out_dout[95:80]}};
        trunc_ln145_211_reg_1077 <= {{layer9_out_dout[111:96]}};
        trunc_ln145_212_reg_1082 <= {{layer9_out_dout[127:112]}};
        trunc_ln145_213_reg_1087 <= {{layer9_out_dout[143:128]}};
        trunc_ln145_214_reg_1092 <= {{layer9_out_dout[159:144]}};
        trunc_ln145_215_reg_1097 <= {{layer9_out_dout[175:160]}};
        trunc_ln145_216_reg_1102 <= {{layer9_out_dout[191:176]}};
        trunc_ln145_217_reg_1107 <= {{layer9_out_dout[207:192]}};
        trunc_ln145_218_reg_1112 <= {{layer9_out_dout[223:208]}};
        trunc_ln145_219_reg_1117 <= {{layer9_out_dout[239:224]}};
        trunc_ln145_220_reg_1122 <= {{layer9_out_dout[255:240]}};
        trunc_ln145_reg_1047 <= trunc_ln145_fu_869_p1;
        trunc_ln145_s_reg_1052 <= {{layer9_out_dout[31:16]}};
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer10_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_write;
    end else begin
        layer10_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_863_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer9_out_blk_n = layer9_out_empty_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer9_out_read = 1'b1;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln51_fu_863_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_857_p2 = (indvar_flatten_reg_462 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call20 = ((icmp_ln51_fu_863_p2 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_ap_start_reg;

assign icmp_ln51_fu_863_p2 = ((indvar_flatten_reg_462 == 12'd3600) ? 1'b1 : 1'b0);

assign layer10_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_41_15_5_3_0_32u_config10_s_fu_473_layer10_out_din;

assign start_out = real_start;

assign trunc_ln145_fu_869_p1 = layer9_out_dout[15:0];

endmodule //myproject_conv_2d_cl_array_array_ap_fixed_41_15_5_3_0_32u_config10_s
