// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_3_5_3_0_32u_relu_config17_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_dout,
        data_empty_n,
        data_read,
        res_din,
        res_full_n,
        res_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [2047:0] data_dout;
input   data_empty_n;
output   data_read;
output  [511:0] res_din;
input   res_full_n;
output   res_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_read;
reg res_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln41_reg_1456;
reg    res_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln41_reg_1456_pp0_iter1_reg;
reg   [11:0] i_reg_309;
wire   [11:0] i_4_fu_320_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln41_fu_326_p2;
wire   [15:0] out_data_97_fu_662_p3;
reg   [15:0] out_data_97_reg_1460;
wire   [15:0] out_data_99_fu_686_p3;
reg   [15:0] out_data_99_reg_1465;
wire   [15:0] out_data_101_fu_710_p3;
reg   [15:0] out_data_101_reg_1470;
wire   [15:0] out_data_103_fu_734_p3;
reg   [15:0] out_data_103_reg_1475;
wire   [15:0] out_data_105_fu_758_p3;
reg   [15:0] out_data_105_reg_1480;
wire   [15:0] out_data_107_fu_782_p3;
reg   [15:0] out_data_107_reg_1485;
wire   [15:0] out_data_109_fu_806_p3;
reg   [15:0] out_data_109_reg_1490;
wire   [15:0] out_data_111_fu_830_p3;
reg   [15:0] out_data_111_reg_1495;
wire   [15:0] out_data_113_fu_854_p3;
reg   [15:0] out_data_113_reg_1500;
wire   [15:0] out_data_115_fu_878_p3;
reg   [15:0] out_data_115_reg_1505;
wire   [15:0] out_data_117_fu_902_p3;
reg   [15:0] out_data_117_reg_1510;
wire   [15:0] out_data_119_fu_926_p3;
reg   [15:0] out_data_119_reg_1515;
wire   [15:0] out_data_121_fu_950_p3;
reg   [15:0] out_data_121_reg_1520;
wire   [15:0] out_data_123_fu_974_p3;
reg   [15:0] out_data_123_reg_1525;
wire   [15:0] out_data_125_fu_998_p3;
reg   [15:0] out_data_125_reg_1530;
wire   [15:0] out_data_127_fu_1022_p3;
reg   [15:0] out_data_127_reg_1535;
wire   [15:0] out_data_129_fu_1046_p3;
reg   [15:0] out_data_129_reg_1540;
wire   [15:0] out_data_131_fu_1070_p3;
reg   [15:0] out_data_131_reg_1545;
wire   [15:0] out_data_133_fu_1094_p3;
reg   [15:0] out_data_133_reg_1550;
wire   [15:0] out_data_135_fu_1118_p3;
reg   [15:0] out_data_135_reg_1555;
wire   [15:0] out_data_137_fu_1142_p3;
reg   [15:0] out_data_137_reg_1560;
wire   [15:0] out_data_139_fu_1166_p3;
reg   [15:0] out_data_139_reg_1565;
wire   [15:0] out_data_141_fu_1190_p3;
reg   [15:0] out_data_141_reg_1570;
wire   [15:0] out_data_143_fu_1214_p3;
reg   [15:0] out_data_143_reg_1575;
wire   [15:0] out_data_145_fu_1238_p3;
reg   [15:0] out_data_145_reg_1580;
wire   [15:0] out_data_147_fu_1262_p3;
reg   [15:0] out_data_147_reg_1585;
wire   [15:0] out_data_149_fu_1286_p3;
reg   [15:0] out_data_149_reg_1590;
wire   [15:0] out_data_151_fu_1310_p3;
reg   [15:0] out_data_151_reg_1595;
wire   [15:0] out_data_153_fu_1334_p3;
reg   [15:0] out_data_153_reg_1600;
wire   [15:0] out_data_155_fu_1358_p3;
reg   [15:0] out_data_155_reg_1605;
wire   [15:0] out_data_157_fu_1382_p3;
reg   [15:0] out_data_157_reg_1610;
wire   [15:0] out_data_159_fu_1406_p3;
reg   [15:0] out_data_159_reg_1615;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire   [41:0] trunc_ln145_fu_332_p1;
wire   [0:0] icmp_ln1494_fu_646_p2;
wire   [15:0] out_data_fu_652_p4;
wire   [41:0] trunc_ln145_s_fu_336_p4;
wire   [0:0] icmp_ln1494_42_fu_670_p2;
wire   [15:0] out_data_98_fu_676_p4;
wire   [41:0] trunc_ln145_36_fu_346_p4;
wire   [0:0] icmp_ln1494_43_fu_694_p2;
wire   [15:0] out_data_100_fu_700_p4;
wire   [41:0] trunc_ln145_37_fu_356_p4;
wire   [0:0] icmp_ln1494_44_fu_718_p2;
wire   [15:0] out_data_102_fu_724_p4;
wire   [41:0] trunc_ln145_38_fu_366_p4;
wire   [0:0] icmp_ln1494_45_fu_742_p2;
wire   [15:0] out_data_104_fu_748_p4;
wire   [41:0] trunc_ln145_39_fu_376_p4;
wire   [0:0] icmp_ln1494_46_fu_766_p2;
wire   [15:0] out_data_106_fu_772_p4;
wire   [41:0] trunc_ln145_40_fu_386_p4;
wire   [0:0] icmp_ln1494_47_fu_790_p2;
wire   [15:0] out_data_108_fu_796_p4;
wire   [41:0] trunc_ln145_41_fu_396_p4;
wire   [0:0] icmp_ln1494_48_fu_814_p2;
wire   [15:0] out_data_110_fu_820_p4;
wire   [41:0] trunc_ln145_42_fu_406_p4;
wire   [0:0] icmp_ln1494_49_fu_838_p2;
wire   [15:0] out_data_112_fu_844_p4;
wire   [41:0] trunc_ln145_43_fu_416_p4;
wire   [0:0] icmp_ln1494_50_fu_862_p2;
wire   [15:0] out_data_114_fu_868_p4;
wire   [41:0] trunc_ln145_44_fu_426_p4;
wire   [0:0] icmp_ln1494_51_fu_886_p2;
wire   [15:0] out_data_116_fu_892_p4;
wire   [41:0] trunc_ln145_45_fu_436_p4;
wire   [0:0] icmp_ln1494_52_fu_910_p2;
wire   [15:0] out_data_118_fu_916_p4;
wire   [41:0] trunc_ln145_46_fu_446_p4;
wire   [0:0] icmp_ln1494_53_fu_934_p2;
wire   [15:0] out_data_120_fu_940_p4;
wire   [41:0] trunc_ln145_47_fu_456_p4;
wire   [0:0] icmp_ln1494_54_fu_958_p2;
wire   [15:0] out_data_122_fu_964_p4;
wire   [41:0] trunc_ln145_48_fu_466_p4;
wire   [0:0] icmp_ln1494_55_fu_982_p2;
wire   [15:0] out_data_124_fu_988_p4;
wire   [41:0] trunc_ln145_49_fu_476_p4;
wire   [0:0] icmp_ln1494_56_fu_1006_p2;
wire   [15:0] out_data_126_fu_1012_p4;
wire   [41:0] trunc_ln145_50_fu_486_p4;
wire   [0:0] icmp_ln1494_57_fu_1030_p2;
wire   [15:0] out_data_128_fu_1036_p4;
wire   [41:0] trunc_ln145_51_fu_496_p4;
wire   [0:0] icmp_ln1494_58_fu_1054_p2;
wire   [15:0] out_data_130_fu_1060_p4;
wire   [41:0] trunc_ln145_52_fu_506_p4;
wire   [0:0] icmp_ln1494_59_fu_1078_p2;
wire   [15:0] out_data_132_fu_1084_p4;
wire   [41:0] trunc_ln145_53_fu_516_p4;
wire   [0:0] icmp_ln1494_60_fu_1102_p2;
wire   [15:0] out_data_134_fu_1108_p4;
wire   [41:0] trunc_ln145_54_fu_526_p4;
wire   [0:0] icmp_ln1494_61_fu_1126_p2;
wire   [15:0] out_data_136_fu_1132_p4;
wire   [41:0] trunc_ln145_55_fu_536_p4;
wire   [0:0] icmp_ln1494_62_fu_1150_p2;
wire   [15:0] out_data_138_fu_1156_p4;
wire   [41:0] trunc_ln145_56_fu_546_p4;
wire   [0:0] icmp_ln1494_63_fu_1174_p2;
wire   [15:0] out_data_140_fu_1180_p4;
wire   [41:0] trunc_ln145_57_fu_556_p4;
wire   [0:0] icmp_ln1494_64_fu_1198_p2;
wire   [15:0] out_data_142_fu_1204_p4;
wire   [41:0] trunc_ln145_58_fu_566_p4;
wire   [0:0] icmp_ln1494_65_fu_1222_p2;
wire   [15:0] out_data_144_fu_1228_p4;
wire   [41:0] trunc_ln145_59_fu_576_p4;
wire   [0:0] icmp_ln1494_66_fu_1246_p2;
wire   [15:0] out_data_146_fu_1252_p4;
wire   [41:0] trunc_ln145_60_fu_586_p4;
wire   [0:0] icmp_ln1494_67_fu_1270_p2;
wire   [15:0] out_data_148_fu_1276_p4;
wire   [41:0] trunc_ln145_61_fu_596_p4;
wire   [0:0] icmp_ln1494_68_fu_1294_p2;
wire   [15:0] out_data_150_fu_1300_p4;
wire   [41:0] trunc_ln145_62_fu_606_p4;
wire   [0:0] icmp_ln1494_69_fu_1318_p2;
wire   [15:0] out_data_152_fu_1324_p4;
wire   [41:0] trunc_ln145_63_fu_616_p4;
wire   [0:0] icmp_ln1494_70_fu_1342_p2;
wire   [15:0] out_data_154_fu_1348_p4;
wire   [41:0] trunc_ln145_64_fu_626_p4;
wire   [0:0] icmp_ln1494_71_fu_1366_p2;
wire   [15:0] out_data_156_fu_1372_p4;
wire   [41:0] trunc_ln145_65_fu_636_p4;
wire   [0:0] icmp_ln1494_72_fu_1390_p2;
wire   [15:0] out_data_158_fu_1396_p4;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_326_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_309 <= i_4_fu_320_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_309 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln41_reg_1456 <= icmp_ln41_fu_326_p2;
        icmp_ln41_reg_1456_pp0_iter1_reg <= icmp_ln41_reg_1456;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_1456 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_101_reg_1470 <= out_data_101_fu_710_p3;
        out_data_103_reg_1475 <= out_data_103_fu_734_p3;
        out_data_105_reg_1480 <= out_data_105_fu_758_p3;
        out_data_107_reg_1485 <= out_data_107_fu_782_p3;
        out_data_109_reg_1490 <= out_data_109_fu_806_p3;
        out_data_111_reg_1495 <= out_data_111_fu_830_p3;
        out_data_113_reg_1500 <= out_data_113_fu_854_p3;
        out_data_115_reg_1505 <= out_data_115_fu_878_p3;
        out_data_117_reg_1510 <= out_data_117_fu_902_p3;
        out_data_119_reg_1515 <= out_data_119_fu_926_p3;
        out_data_121_reg_1520 <= out_data_121_fu_950_p3;
        out_data_123_reg_1525 <= out_data_123_fu_974_p3;
        out_data_125_reg_1530 <= out_data_125_fu_998_p3;
        out_data_127_reg_1535 <= out_data_127_fu_1022_p3;
        out_data_129_reg_1540 <= out_data_129_fu_1046_p3;
        out_data_131_reg_1545 <= out_data_131_fu_1070_p3;
        out_data_133_reg_1550 <= out_data_133_fu_1094_p3;
        out_data_135_reg_1555 <= out_data_135_fu_1118_p3;
        out_data_137_reg_1560 <= out_data_137_fu_1142_p3;
        out_data_139_reg_1565 <= out_data_139_fu_1166_p3;
        out_data_141_reg_1570 <= out_data_141_fu_1190_p3;
        out_data_143_reg_1575 <= out_data_143_fu_1214_p3;
        out_data_145_reg_1580 <= out_data_145_fu_1238_p3;
        out_data_147_reg_1585 <= out_data_147_fu_1262_p3;
        out_data_149_reg_1590 <= out_data_149_fu_1286_p3;
        out_data_151_reg_1595 <= out_data_151_fu_1310_p3;
        out_data_153_reg_1600 <= out_data_153_fu_1334_p3;
        out_data_155_reg_1605 <= out_data_155_fu_1358_p3;
        out_data_157_reg_1610 <= out_data_157_fu_1382_p3;
        out_data_159_reg_1615 <= out_data_159_fu_1406_p3;
        out_data_97_reg_1460 <= out_data_97_fu_662_p3;
        out_data_99_reg_1465 <= out_data_99_fu_686_p3;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_326_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1456 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_blk_n = data_empty_n;
    end else begin
        data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1456 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_read = 1'b1;
    end else begin
        data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        res_blk_n = res_full_n;
    end else begin
        res_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_write = 1'b1;
    end else begin
        res_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln41_fu_326_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln41_fu_326_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_1456 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_1456 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_1456 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln41_reg_1456 == 1'd0) & (data_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln41_reg_1456_pp0_iter1_reg == 1'd0) & (res_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign i_4_fu_320_p2 = (i_reg_309 + 12'd1);

assign icmp_ln1494_42_fu_670_p2 = (($signed(trunc_ln145_s_fu_336_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_43_fu_694_p2 = (($signed(trunc_ln145_36_fu_346_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_44_fu_718_p2 = (($signed(trunc_ln145_37_fu_356_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_45_fu_742_p2 = (($signed(trunc_ln145_38_fu_366_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_46_fu_766_p2 = (($signed(trunc_ln145_39_fu_376_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_47_fu_790_p2 = (($signed(trunc_ln145_40_fu_386_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_48_fu_814_p2 = (($signed(trunc_ln145_41_fu_396_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_49_fu_838_p2 = (($signed(trunc_ln145_42_fu_406_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_50_fu_862_p2 = (($signed(trunc_ln145_43_fu_416_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_51_fu_886_p2 = (($signed(trunc_ln145_44_fu_426_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_52_fu_910_p2 = (($signed(trunc_ln145_45_fu_436_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_53_fu_934_p2 = (($signed(trunc_ln145_46_fu_446_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_54_fu_958_p2 = (($signed(trunc_ln145_47_fu_456_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_55_fu_982_p2 = (($signed(trunc_ln145_48_fu_466_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_56_fu_1006_p2 = (($signed(trunc_ln145_49_fu_476_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_57_fu_1030_p2 = (($signed(trunc_ln145_50_fu_486_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_58_fu_1054_p2 = (($signed(trunc_ln145_51_fu_496_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_59_fu_1078_p2 = (($signed(trunc_ln145_52_fu_506_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_60_fu_1102_p2 = (($signed(trunc_ln145_53_fu_516_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_61_fu_1126_p2 = (($signed(trunc_ln145_54_fu_526_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_62_fu_1150_p2 = (($signed(trunc_ln145_55_fu_536_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_63_fu_1174_p2 = (($signed(trunc_ln145_56_fu_546_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_64_fu_1198_p2 = (($signed(trunc_ln145_57_fu_556_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_65_fu_1222_p2 = (($signed(trunc_ln145_58_fu_566_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_66_fu_1246_p2 = (($signed(trunc_ln145_59_fu_576_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_67_fu_1270_p2 = (($signed(trunc_ln145_60_fu_586_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_68_fu_1294_p2 = (($signed(trunc_ln145_61_fu_596_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_69_fu_1318_p2 = (($signed(trunc_ln145_62_fu_606_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_70_fu_1342_p2 = (($signed(trunc_ln145_63_fu_616_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_71_fu_1366_p2 = (($signed(trunc_ln145_64_fu_626_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_72_fu_1390_p2 = (($signed(trunc_ln145_65_fu_636_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_646_p2 = (($signed(trunc_ln145_fu_332_p1) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_326_p2 = ((i_reg_309 == 12'd3136) ? 1'b1 : 1'b0);

assign out_data_100_fu_700_p4 = {{data_dout[156:141]}};

assign out_data_101_fu_710_p3 = ((icmp_ln1494_43_fu_694_p2[0:0] == 1'b1) ? out_data_100_fu_700_p4 : 16'd0);

assign out_data_102_fu_724_p4 = {{data_dout[220:205]}};

assign out_data_103_fu_734_p3 = ((icmp_ln1494_44_fu_718_p2[0:0] == 1'b1) ? out_data_102_fu_724_p4 : 16'd0);

assign out_data_104_fu_748_p4 = {{data_dout[284:269]}};

assign out_data_105_fu_758_p3 = ((icmp_ln1494_45_fu_742_p2[0:0] == 1'b1) ? out_data_104_fu_748_p4 : 16'd0);

assign out_data_106_fu_772_p4 = {{data_dout[348:333]}};

assign out_data_107_fu_782_p3 = ((icmp_ln1494_46_fu_766_p2[0:0] == 1'b1) ? out_data_106_fu_772_p4 : 16'd0);

assign out_data_108_fu_796_p4 = {{data_dout[412:397]}};

assign out_data_109_fu_806_p3 = ((icmp_ln1494_47_fu_790_p2[0:0] == 1'b1) ? out_data_108_fu_796_p4 : 16'd0);

assign out_data_110_fu_820_p4 = {{data_dout[476:461]}};

assign out_data_111_fu_830_p3 = ((icmp_ln1494_48_fu_814_p2[0:0] == 1'b1) ? out_data_110_fu_820_p4 : 16'd0);

assign out_data_112_fu_844_p4 = {{data_dout[540:525]}};

assign out_data_113_fu_854_p3 = ((icmp_ln1494_49_fu_838_p2[0:0] == 1'b1) ? out_data_112_fu_844_p4 : 16'd0);

assign out_data_114_fu_868_p4 = {{data_dout[604:589]}};

assign out_data_115_fu_878_p3 = ((icmp_ln1494_50_fu_862_p2[0:0] == 1'b1) ? out_data_114_fu_868_p4 : 16'd0);

assign out_data_116_fu_892_p4 = {{data_dout[668:653]}};

assign out_data_117_fu_902_p3 = ((icmp_ln1494_51_fu_886_p2[0:0] == 1'b1) ? out_data_116_fu_892_p4 : 16'd0);

assign out_data_118_fu_916_p4 = {{data_dout[732:717]}};

assign out_data_119_fu_926_p3 = ((icmp_ln1494_52_fu_910_p2[0:0] == 1'b1) ? out_data_118_fu_916_p4 : 16'd0);

assign out_data_120_fu_940_p4 = {{data_dout[796:781]}};

assign out_data_121_fu_950_p3 = ((icmp_ln1494_53_fu_934_p2[0:0] == 1'b1) ? out_data_120_fu_940_p4 : 16'd0);

assign out_data_122_fu_964_p4 = {{data_dout[860:845]}};

assign out_data_123_fu_974_p3 = ((icmp_ln1494_54_fu_958_p2[0:0] == 1'b1) ? out_data_122_fu_964_p4 : 16'd0);

assign out_data_124_fu_988_p4 = {{data_dout[924:909]}};

assign out_data_125_fu_998_p3 = ((icmp_ln1494_55_fu_982_p2[0:0] == 1'b1) ? out_data_124_fu_988_p4 : 16'd0);

assign out_data_126_fu_1012_p4 = {{data_dout[988:973]}};

assign out_data_127_fu_1022_p3 = ((icmp_ln1494_56_fu_1006_p2[0:0] == 1'b1) ? out_data_126_fu_1012_p4 : 16'd0);

assign out_data_128_fu_1036_p4 = {{data_dout[1052:1037]}};

assign out_data_129_fu_1046_p3 = ((icmp_ln1494_57_fu_1030_p2[0:0] == 1'b1) ? out_data_128_fu_1036_p4 : 16'd0);

assign out_data_130_fu_1060_p4 = {{data_dout[1116:1101]}};

assign out_data_131_fu_1070_p3 = ((icmp_ln1494_58_fu_1054_p2[0:0] == 1'b1) ? out_data_130_fu_1060_p4 : 16'd0);

assign out_data_132_fu_1084_p4 = {{data_dout[1180:1165]}};

assign out_data_133_fu_1094_p3 = ((icmp_ln1494_59_fu_1078_p2[0:0] == 1'b1) ? out_data_132_fu_1084_p4 : 16'd0);

assign out_data_134_fu_1108_p4 = {{data_dout[1244:1229]}};

assign out_data_135_fu_1118_p3 = ((icmp_ln1494_60_fu_1102_p2[0:0] == 1'b1) ? out_data_134_fu_1108_p4 : 16'd0);

assign out_data_136_fu_1132_p4 = {{data_dout[1308:1293]}};

assign out_data_137_fu_1142_p3 = ((icmp_ln1494_61_fu_1126_p2[0:0] == 1'b1) ? out_data_136_fu_1132_p4 : 16'd0);

assign out_data_138_fu_1156_p4 = {{data_dout[1372:1357]}};

assign out_data_139_fu_1166_p3 = ((icmp_ln1494_62_fu_1150_p2[0:0] == 1'b1) ? out_data_138_fu_1156_p4 : 16'd0);

assign out_data_140_fu_1180_p4 = {{data_dout[1436:1421]}};

assign out_data_141_fu_1190_p3 = ((icmp_ln1494_63_fu_1174_p2[0:0] == 1'b1) ? out_data_140_fu_1180_p4 : 16'd0);

assign out_data_142_fu_1204_p4 = {{data_dout[1500:1485]}};

assign out_data_143_fu_1214_p3 = ((icmp_ln1494_64_fu_1198_p2[0:0] == 1'b1) ? out_data_142_fu_1204_p4 : 16'd0);

assign out_data_144_fu_1228_p4 = {{data_dout[1564:1549]}};

assign out_data_145_fu_1238_p3 = ((icmp_ln1494_65_fu_1222_p2[0:0] == 1'b1) ? out_data_144_fu_1228_p4 : 16'd0);

assign out_data_146_fu_1252_p4 = {{data_dout[1628:1613]}};

assign out_data_147_fu_1262_p3 = ((icmp_ln1494_66_fu_1246_p2[0:0] == 1'b1) ? out_data_146_fu_1252_p4 : 16'd0);

assign out_data_148_fu_1276_p4 = {{data_dout[1692:1677]}};

assign out_data_149_fu_1286_p3 = ((icmp_ln1494_67_fu_1270_p2[0:0] == 1'b1) ? out_data_148_fu_1276_p4 : 16'd0);

assign out_data_150_fu_1300_p4 = {{data_dout[1756:1741]}};

assign out_data_151_fu_1310_p3 = ((icmp_ln1494_68_fu_1294_p2[0:0] == 1'b1) ? out_data_150_fu_1300_p4 : 16'd0);

assign out_data_152_fu_1324_p4 = {{data_dout[1820:1805]}};

assign out_data_153_fu_1334_p3 = ((icmp_ln1494_69_fu_1318_p2[0:0] == 1'b1) ? out_data_152_fu_1324_p4 : 16'd0);

assign out_data_154_fu_1348_p4 = {{data_dout[1884:1869]}};

assign out_data_155_fu_1358_p3 = ((icmp_ln1494_70_fu_1342_p2[0:0] == 1'b1) ? out_data_154_fu_1348_p4 : 16'd0);

assign out_data_156_fu_1372_p4 = {{data_dout[1948:1933]}};

assign out_data_157_fu_1382_p3 = ((icmp_ln1494_71_fu_1366_p2[0:0] == 1'b1) ? out_data_156_fu_1372_p4 : 16'd0);

assign out_data_158_fu_1396_p4 = {{data_dout[2012:1997]}};

assign out_data_159_fu_1406_p3 = ((icmp_ln1494_72_fu_1390_p2[0:0] == 1'b1) ? out_data_158_fu_1396_p4 : 16'd0);

assign out_data_97_fu_662_p3 = ((icmp_ln1494_fu_646_p2[0:0] == 1'b1) ? out_data_fu_652_p4 : 16'd0);

assign out_data_98_fu_676_p4 = {{data_dout[92:77]}};

assign out_data_99_fu_686_p3 = ((icmp_ln1494_42_fu_670_p2[0:0] == 1'b1) ? out_data_98_fu_676_p4 : 16'd0);

assign out_data_fu_652_p4 = {{data_dout[28:13]}};

assign res_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{out_data_159_reg_1615}, {out_data_157_reg_1610}}, {out_data_155_reg_1605}}, {out_data_153_reg_1600}}, {out_data_151_reg_1595}}, {out_data_149_reg_1590}}, {out_data_147_reg_1585}}, {out_data_145_reg_1580}}, {out_data_143_reg_1575}}, {out_data_141_reg_1570}}, {out_data_139_reg_1565}}, {out_data_137_reg_1560}}, {out_data_135_reg_1555}}, {out_data_133_reg_1550}}, {out_data_131_reg_1545}}, {out_data_129_reg_1540}}, {out_data_127_reg_1535}}, {out_data_125_reg_1530}}, {out_data_123_reg_1525}}, {out_data_121_reg_1520}}, {out_data_119_reg_1515}}, {out_data_117_reg_1510}}, {out_data_115_reg_1505}}, {out_data_113_reg_1500}}, {out_data_111_reg_1495}}, {out_data_109_reg_1490}}, {out_data_107_reg_1485}}, {out_data_105_reg_1480}}, {out_data_103_reg_1475}}, {out_data_101_reg_1470}}, {out_data_99_reg_1465}}, {out_data_97_reg_1460}};

assign start_out = real_start;

assign trunc_ln145_36_fu_346_p4 = {{data_dout[169:128]}};

assign trunc_ln145_37_fu_356_p4 = {{data_dout[233:192]}};

assign trunc_ln145_38_fu_366_p4 = {{data_dout[297:256]}};

assign trunc_ln145_39_fu_376_p4 = {{data_dout[361:320]}};

assign trunc_ln145_40_fu_386_p4 = {{data_dout[425:384]}};

assign trunc_ln145_41_fu_396_p4 = {{data_dout[489:448]}};

assign trunc_ln145_42_fu_406_p4 = {{data_dout[553:512]}};

assign trunc_ln145_43_fu_416_p4 = {{data_dout[617:576]}};

assign trunc_ln145_44_fu_426_p4 = {{data_dout[681:640]}};

assign trunc_ln145_45_fu_436_p4 = {{data_dout[745:704]}};

assign trunc_ln145_46_fu_446_p4 = {{data_dout[809:768]}};

assign trunc_ln145_47_fu_456_p4 = {{data_dout[873:832]}};

assign trunc_ln145_48_fu_466_p4 = {{data_dout[937:896]}};

assign trunc_ln145_49_fu_476_p4 = {{data_dout[1001:960]}};

assign trunc_ln145_50_fu_486_p4 = {{data_dout[1065:1024]}};

assign trunc_ln145_51_fu_496_p4 = {{data_dout[1129:1088]}};

assign trunc_ln145_52_fu_506_p4 = {{data_dout[1193:1152]}};

assign trunc_ln145_53_fu_516_p4 = {{data_dout[1257:1216]}};

assign trunc_ln145_54_fu_526_p4 = {{data_dout[1321:1280]}};

assign trunc_ln145_55_fu_536_p4 = {{data_dout[1385:1344]}};

assign trunc_ln145_56_fu_546_p4 = {{data_dout[1449:1408]}};

assign trunc_ln145_57_fu_556_p4 = {{data_dout[1513:1472]}};

assign trunc_ln145_58_fu_566_p4 = {{data_dout[1577:1536]}};

assign trunc_ln145_59_fu_576_p4 = {{data_dout[1641:1600]}};

assign trunc_ln145_60_fu_586_p4 = {{data_dout[1705:1664]}};

assign trunc_ln145_61_fu_596_p4 = {{data_dout[1769:1728]}};

assign trunc_ln145_62_fu_606_p4 = {{data_dout[1833:1792]}};

assign trunc_ln145_63_fu_616_p4 = {{data_dout[1897:1856]}};

assign trunc_ln145_64_fu_626_p4 = {{data_dout[1961:1920]}};

assign trunc_ln145_65_fu_636_p4 = {{data_dout[2025:1984]}};

assign trunc_ln145_fu_332_p1 = data_dout[41:0];

assign trunc_ln145_s_fu_336_p4 = {{data_dout[105:64]}};

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_3_5_3_0_32u_relu_config17_s
