// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        kernel_data_V_11_8_i,
        kernel_data_V_11_8_o,
        kernel_data_V_11_8_o_ap_vld,
        kernel_data_V_11_0,
        kernel_data_V_11_0_ap_vld,
        kernel_data_V_11_9_i,
        kernel_data_V_11_9_o,
        kernel_data_V_11_9_o_ap_vld,
        kernel_data_V_11_1,
        kernel_data_V_11_1_ap_vld,
        kernel_data_V_11_10_i,
        kernel_data_V_11_10_o,
        kernel_data_V_11_10_o_ap_vld,
        kernel_data_V_11_2,
        kernel_data_V_11_2_ap_vld,
        kernel_data_V_11_11_i,
        kernel_data_V_11_11_o,
        kernel_data_V_11_11_o_ap_vld,
        kernel_data_V_11_3,
        kernel_data_V_11_3_ap_vld,
        kernel_data_V_11_12_i,
        kernel_data_V_11_12_o,
        kernel_data_V_11_12_o_ap_vld,
        kernel_data_V_11_4,
        kernel_data_V_11_4_ap_vld,
        kernel_data_V_11_13_i,
        kernel_data_V_11_13_o,
        kernel_data_V_11_13_o_ap_vld,
        kernel_data_V_11_5,
        kernel_data_V_11_5_ap_vld,
        kernel_data_V_11_14_i,
        kernel_data_V_11_14_o,
        kernel_data_V_11_14_o_ap_vld,
        kernel_data_V_11_6,
        kernel_data_V_11_6_ap_vld,
        kernel_data_V_11_15_i,
        kernel_data_V_11_15_o,
        kernel_data_V_11_15_o_ap_vld,
        kernel_data_V_11_7,
        kernel_data_V_11_7_ap_vld,
        kernel_data_V_11_32_i,
        kernel_data_V_11_32_o,
        kernel_data_V_11_32_o_ap_vld,
        kernel_data_V_11_24,
        kernel_data_V_11_24_ap_vld,
        kernel_data_V_11_33_i,
        kernel_data_V_11_33_o,
        kernel_data_V_11_33_o_ap_vld,
        kernel_data_V_11_25,
        kernel_data_V_11_25_ap_vld,
        kernel_data_V_11_34_i,
        kernel_data_V_11_34_o,
        kernel_data_V_11_34_o_ap_vld,
        kernel_data_V_11_26,
        kernel_data_V_11_26_ap_vld,
        kernel_data_V_11_35_i,
        kernel_data_V_11_35_o,
        kernel_data_V_11_35_o_ap_vld,
        kernel_data_V_11_27,
        kernel_data_V_11_27_ap_vld,
        kernel_data_V_11_36_i,
        kernel_data_V_11_36_o,
        kernel_data_V_11_36_o_ap_vld,
        kernel_data_V_11_28,
        kernel_data_V_11_28_ap_vld,
        kernel_data_V_11_37_i,
        kernel_data_V_11_37_o,
        kernel_data_V_11_37_o_ap_vld,
        kernel_data_V_11_29,
        kernel_data_V_11_29_ap_vld,
        kernel_data_V_11_38_i,
        kernel_data_V_11_38_o,
        kernel_data_V_11_38_o_ap_vld,
        kernel_data_V_11_30,
        kernel_data_V_11_30_ap_vld,
        kernel_data_V_11_39_i,
        kernel_data_V_11_39_o,
        kernel_data_V_11_39_o_ap_vld,
        kernel_data_V_11_31,
        kernel_data_V_11_31_ap_vld,
        kernel_data_V_11_56_i,
        kernel_data_V_11_56_o,
        kernel_data_V_11_56_o_ap_vld,
        kernel_data_V_11_48,
        kernel_data_V_11_48_ap_vld,
        kernel_data_V_11_57_i,
        kernel_data_V_11_57_o,
        kernel_data_V_11_57_o_ap_vld,
        kernel_data_V_11_49,
        kernel_data_V_11_49_ap_vld,
        kernel_data_V_11_58_i,
        kernel_data_V_11_58_o,
        kernel_data_V_11_58_o_ap_vld,
        kernel_data_V_11_50,
        kernel_data_V_11_50_ap_vld,
        kernel_data_V_11_59_i,
        kernel_data_V_11_59_o,
        kernel_data_V_11_59_o_ap_vld,
        kernel_data_V_11_51,
        kernel_data_V_11_51_ap_vld,
        kernel_data_V_11_60_i,
        kernel_data_V_11_60_o,
        kernel_data_V_11_60_o_ap_vld,
        kernel_data_V_11_52,
        kernel_data_V_11_52_ap_vld,
        kernel_data_V_11_61_i,
        kernel_data_V_11_61_o,
        kernel_data_V_11_61_o_ap_vld,
        kernel_data_V_11_53,
        kernel_data_V_11_53_ap_vld,
        kernel_data_V_11_62_i,
        kernel_data_V_11_62_o,
        kernel_data_V_11_62_o_ap_vld,
        kernel_data_V_11_54,
        kernel_data_V_11_54_ap_vld,
        kernel_data_V_11_63_i,
        kernel_data_V_11_63_o,
        kernel_data_V_11_63_o_ap_vld,
        kernel_data_V_11_55,
        kernel_data_V_11_55_ap_vld,
        kernel_data_V_11_16_i,
        kernel_data_V_11_16_o,
        kernel_data_V_11_16_o_ap_vld,
        kernel_data_V_11_17_i,
        kernel_data_V_11_17_o,
        kernel_data_V_11_17_o_ap_vld,
        kernel_data_V_11_18_i,
        kernel_data_V_11_18_o,
        kernel_data_V_11_18_o_ap_vld,
        kernel_data_V_11_19_i,
        kernel_data_V_11_19_o,
        kernel_data_V_11_19_o_ap_vld,
        kernel_data_V_11_20_i,
        kernel_data_V_11_20_o,
        kernel_data_V_11_20_o_ap_vld,
        kernel_data_V_11_21_i,
        kernel_data_V_11_21_o,
        kernel_data_V_11_21_o_ap_vld,
        kernel_data_V_11_22_i,
        kernel_data_V_11_22_o,
        kernel_data_V_11_22_o_ap_vld,
        kernel_data_V_11_23_i,
        kernel_data_V_11_23_o,
        kernel_data_V_11_23_o_ap_vld,
        kernel_data_V_11_40_i,
        kernel_data_V_11_40_o,
        kernel_data_V_11_40_o_ap_vld,
        kernel_data_V_11_41_i,
        kernel_data_V_11_41_o,
        kernel_data_V_11_41_o_ap_vld,
        kernel_data_V_11_42_i,
        kernel_data_V_11_42_o,
        kernel_data_V_11_42_o_ap_vld,
        kernel_data_V_11_43_i,
        kernel_data_V_11_43_o,
        kernel_data_V_11_43_o_ap_vld,
        kernel_data_V_11_44_i,
        kernel_data_V_11_44_o,
        kernel_data_V_11_44_o_ap_vld,
        kernel_data_V_11_45_i,
        kernel_data_V_11_45_o,
        kernel_data_V_11_45_o_ap_vld,
        kernel_data_V_11_46_i,
        kernel_data_V_11_46_o,
        kernel_data_V_11_46_o_ap_vld,
        kernel_data_V_11_47_i,
        kernel_data_V_11_47_o,
        kernel_data_V_11_47_o_ap_vld,
        kernel_data_V_11_64_i,
        kernel_data_V_11_64_o,
        kernel_data_V_11_64_o_ap_vld,
        kernel_data_V_11_65_i,
        kernel_data_V_11_65_o,
        kernel_data_V_11_65_o_ap_vld,
        kernel_data_V_11_66_i,
        kernel_data_V_11_66_o,
        kernel_data_V_11_66_o_ap_vld,
        kernel_data_V_11_67_i,
        kernel_data_V_11_67_o,
        kernel_data_V_11_67_o_ap_vld,
        kernel_data_V_11_68_i,
        kernel_data_V_11_68_o,
        kernel_data_V_11_68_o_ap_vld,
        kernel_data_V_11_69_i,
        kernel_data_V_11_69_o,
        kernel_data_V_11_69_o_ap_vld,
        kernel_data_V_11_70_i,
        kernel_data_V_11_70_o,
        kernel_data_V_11_70_o_ap_vld,
        kernel_data_V_11_71_i,
        kernel_data_V_11_71_o,
        kernel_data_V_11_71_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] kernel_data_V_11_8_i;
output  [15:0] kernel_data_V_11_8_o;
output   kernel_data_V_11_8_o_ap_vld;
output  [15:0] kernel_data_V_11_0;
output   kernel_data_V_11_0_ap_vld;
input  [15:0] kernel_data_V_11_9_i;
output  [15:0] kernel_data_V_11_9_o;
output   kernel_data_V_11_9_o_ap_vld;
output  [15:0] kernel_data_V_11_1;
output   kernel_data_V_11_1_ap_vld;
input  [15:0] kernel_data_V_11_10_i;
output  [15:0] kernel_data_V_11_10_o;
output   kernel_data_V_11_10_o_ap_vld;
output  [15:0] kernel_data_V_11_2;
output   kernel_data_V_11_2_ap_vld;
input  [15:0] kernel_data_V_11_11_i;
output  [15:0] kernel_data_V_11_11_o;
output   kernel_data_V_11_11_o_ap_vld;
output  [15:0] kernel_data_V_11_3;
output   kernel_data_V_11_3_ap_vld;
input  [15:0] kernel_data_V_11_12_i;
output  [15:0] kernel_data_V_11_12_o;
output   kernel_data_V_11_12_o_ap_vld;
output  [15:0] kernel_data_V_11_4;
output   kernel_data_V_11_4_ap_vld;
input  [15:0] kernel_data_V_11_13_i;
output  [15:0] kernel_data_V_11_13_o;
output   kernel_data_V_11_13_o_ap_vld;
output  [15:0] kernel_data_V_11_5;
output   kernel_data_V_11_5_ap_vld;
input  [15:0] kernel_data_V_11_14_i;
output  [15:0] kernel_data_V_11_14_o;
output   kernel_data_V_11_14_o_ap_vld;
output  [15:0] kernel_data_V_11_6;
output   kernel_data_V_11_6_ap_vld;
input  [15:0] kernel_data_V_11_15_i;
output  [15:0] kernel_data_V_11_15_o;
output   kernel_data_V_11_15_o_ap_vld;
output  [15:0] kernel_data_V_11_7;
output   kernel_data_V_11_7_ap_vld;
input  [15:0] kernel_data_V_11_32_i;
output  [15:0] kernel_data_V_11_32_o;
output   kernel_data_V_11_32_o_ap_vld;
output  [15:0] kernel_data_V_11_24;
output   kernel_data_V_11_24_ap_vld;
input  [15:0] kernel_data_V_11_33_i;
output  [15:0] kernel_data_V_11_33_o;
output   kernel_data_V_11_33_o_ap_vld;
output  [15:0] kernel_data_V_11_25;
output   kernel_data_V_11_25_ap_vld;
input  [15:0] kernel_data_V_11_34_i;
output  [15:0] kernel_data_V_11_34_o;
output   kernel_data_V_11_34_o_ap_vld;
output  [15:0] kernel_data_V_11_26;
output   kernel_data_V_11_26_ap_vld;
input  [15:0] kernel_data_V_11_35_i;
output  [15:0] kernel_data_V_11_35_o;
output   kernel_data_V_11_35_o_ap_vld;
output  [15:0] kernel_data_V_11_27;
output   kernel_data_V_11_27_ap_vld;
input  [15:0] kernel_data_V_11_36_i;
output  [15:0] kernel_data_V_11_36_o;
output   kernel_data_V_11_36_o_ap_vld;
output  [15:0] kernel_data_V_11_28;
output   kernel_data_V_11_28_ap_vld;
input  [15:0] kernel_data_V_11_37_i;
output  [15:0] kernel_data_V_11_37_o;
output   kernel_data_V_11_37_o_ap_vld;
output  [15:0] kernel_data_V_11_29;
output   kernel_data_V_11_29_ap_vld;
input  [15:0] kernel_data_V_11_38_i;
output  [15:0] kernel_data_V_11_38_o;
output   kernel_data_V_11_38_o_ap_vld;
output  [15:0] kernel_data_V_11_30;
output   kernel_data_V_11_30_ap_vld;
input  [15:0] kernel_data_V_11_39_i;
output  [15:0] kernel_data_V_11_39_o;
output   kernel_data_V_11_39_o_ap_vld;
output  [15:0] kernel_data_V_11_31;
output   kernel_data_V_11_31_ap_vld;
input  [15:0] kernel_data_V_11_56_i;
output  [15:0] kernel_data_V_11_56_o;
output   kernel_data_V_11_56_o_ap_vld;
output  [15:0] kernel_data_V_11_48;
output   kernel_data_V_11_48_ap_vld;
input  [15:0] kernel_data_V_11_57_i;
output  [15:0] kernel_data_V_11_57_o;
output   kernel_data_V_11_57_o_ap_vld;
output  [15:0] kernel_data_V_11_49;
output   kernel_data_V_11_49_ap_vld;
input  [15:0] kernel_data_V_11_58_i;
output  [15:0] kernel_data_V_11_58_o;
output   kernel_data_V_11_58_o_ap_vld;
output  [15:0] kernel_data_V_11_50;
output   kernel_data_V_11_50_ap_vld;
input  [15:0] kernel_data_V_11_59_i;
output  [15:0] kernel_data_V_11_59_o;
output   kernel_data_V_11_59_o_ap_vld;
output  [15:0] kernel_data_V_11_51;
output   kernel_data_V_11_51_ap_vld;
input  [15:0] kernel_data_V_11_60_i;
output  [15:0] kernel_data_V_11_60_o;
output   kernel_data_V_11_60_o_ap_vld;
output  [15:0] kernel_data_V_11_52;
output   kernel_data_V_11_52_ap_vld;
input  [15:0] kernel_data_V_11_61_i;
output  [15:0] kernel_data_V_11_61_o;
output   kernel_data_V_11_61_o_ap_vld;
output  [15:0] kernel_data_V_11_53;
output   kernel_data_V_11_53_ap_vld;
input  [15:0] kernel_data_V_11_62_i;
output  [15:0] kernel_data_V_11_62_o;
output   kernel_data_V_11_62_o_ap_vld;
output  [15:0] kernel_data_V_11_54;
output   kernel_data_V_11_54_ap_vld;
input  [15:0] kernel_data_V_11_63_i;
output  [15:0] kernel_data_V_11_63_o;
output   kernel_data_V_11_63_o_ap_vld;
output  [15:0] kernel_data_V_11_55;
output   kernel_data_V_11_55_ap_vld;
input  [15:0] kernel_data_V_11_16_i;
output  [15:0] kernel_data_V_11_16_o;
output   kernel_data_V_11_16_o_ap_vld;
input  [15:0] kernel_data_V_11_17_i;
output  [15:0] kernel_data_V_11_17_o;
output   kernel_data_V_11_17_o_ap_vld;
input  [15:0] kernel_data_V_11_18_i;
output  [15:0] kernel_data_V_11_18_o;
output   kernel_data_V_11_18_o_ap_vld;
input  [15:0] kernel_data_V_11_19_i;
output  [15:0] kernel_data_V_11_19_o;
output   kernel_data_V_11_19_o_ap_vld;
input  [15:0] kernel_data_V_11_20_i;
output  [15:0] kernel_data_V_11_20_o;
output   kernel_data_V_11_20_o_ap_vld;
input  [15:0] kernel_data_V_11_21_i;
output  [15:0] kernel_data_V_11_21_o;
output   kernel_data_V_11_21_o_ap_vld;
input  [15:0] kernel_data_V_11_22_i;
output  [15:0] kernel_data_V_11_22_o;
output   kernel_data_V_11_22_o_ap_vld;
input  [15:0] kernel_data_V_11_23_i;
output  [15:0] kernel_data_V_11_23_o;
output   kernel_data_V_11_23_o_ap_vld;
input  [15:0] kernel_data_V_11_40_i;
output  [15:0] kernel_data_V_11_40_o;
output   kernel_data_V_11_40_o_ap_vld;
input  [15:0] kernel_data_V_11_41_i;
output  [15:0] kernel_data_V_11_41_o;
output   kernel_data_V_11_41_o_ap_vld;
input  [15:0] kernel_data_V_11_42_i;
output  [15:0] kernel_data_V_11_42_o;
output   kernel_data_V_11_42_o_ap_vld;
input  [15:0] kernel_data_V_11_43_i;
output  [15:0] kernel_data_V_11_43_o;
output   kernel_data_V_11_43_o_ap_vld;
input  [15:0] kernel_data_V_11_44_i;
output  [15:0] kernel_data_V_11_44_o;
output   kernel_data_V_11_44_o_ap_vld;
input  [15:0] kernel_data_V_11_45_i;
output  [15:0] kernel_data_V_11_45_o;
output   kernel_data_V_11_45_o_ap_vld;
input  [15:0] kernel_data_V_11_46_i;
output  [15:0] kernel_data_V_11_46_o;
output   kernel_data_V_11_46_o_ap_vld;
input  [15:0] kernel_data_V_11_47_i;
output  [15:0] kernel_data_V_11_47_o;
output   kernel_data_V_11_47_o_ap_vld;
input  [15:0] kernel_data_V_11_64_i;
output  [15:0] kernel_data_V_11_64_o;
output   kernel_data_V_11_64_o_ap_vld;
input  [15:0] kernel_data_V_11_65_i;
output  [15:0] kernel_data_V_11_65_o;
output   kernel_data_V_11_65_o_ap_vld;
input  [15:0] kernel_data_V_11_66_i;
output  [15:0] kernel_data_V_11_66_o;
output   kernel_data_V_11_66_o_ap_vld;
input  [15:0] kernel_data_V_11_67_i;
output  [15:0] kernel_data_V_11_67_o;
output   kernel_data_V_11_67_o_ap_vld;
input  [15:0] kernel_data_V_11_68_i;
output  [15:0] kernel_data_V_11_68_o;
output   kernel_data_V_11_68_o_ap_vld;
input  [15:0] kernel_data_V_11_69_i;
output  [15:0] kernel_data_V_11_69_o;
output   kernel_data_V_11_69_o_ap_vld;
input  [15:0] kernel_data_V_11_70_i;
output  [15:0] kernel_data_V_11_70_o;
output   kernel_data_V_11_70_o_ap_vld;
input  [15:0] kernel_data_V_11_71_i;
output  [15:0] kernel_data_V_11_71_o;
output   kernel_data_V_11_71_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] kernel_data_V_11_8_o;
reg kernel_data_V_11_8_o_ap_vld;
reg kernel_data_V_11_0_ap_vld;
reg[15:0] kernel_data_V_11_9_o;
reg kernel_data_V_11_9_o_ap_vld;
reg kernel_data_V_11_1_ap_vld;
reg[15:0] kernel_data_V_11_10_o;
reg kernel_data_V_11_10_o_ap_vld;
reg kernel_data_V_11_2_ap_vld;
reg[15:0] kernel_data_V_11_11_o;
reg kernel_data_V_11_11_o_ap_vld;
reg kernel_data_V_11_3_ap_vld;
reg[15:0] kernel_data_V_11_12_o;
reg kernel_data_V_11_12_o_ap_vld;
reg kernel_data_V_11_4_ap_vld;
reg[15:0] kernel_data_V_11_13_o;
reg kernel_data_V_11_13_o_ap_vld;
reg kernel_data_V_11_5_ap_vld;
reg[15:0] kernel_data_V_11_14_o;
reg kernel_data_V_11_14_o_ap_vld;
reg kernel_data_V_11_6_ap_vld;
reg[15:0] kernel_data_V_11_15_o;
reg kernel_data_V_11_15_o_ap_vld;
reg kernel_data_V_11_7_ap_vld;
reg[15:0] kernel_data_V_11_32_o;
reg kernel_data_V_11_32_o_ap_vld;
reg kernel_data_V_11_24_ap_vld;
reg[15:0] kernel_data_V_11_33_o;
reg kernel_data_V_11_33_o_ap_vld;
reg kernel_data_V_11_25_ap_vld;
reg[15:0] kernel_data_V_11_34_o;
reg kernel_data_V_11_34_o_ap_vld;
reg kernel_data_V_11_26_ap_vld;
reg[15:0] kernel_data_V_11_35_o;
reg kernel_data_V_11_35_o_ap_vld;
reg kernel_data_V_11_27_ap_vld;
reg[15:0] kernel_data_V_11_36_o;
reg kernel_data_V_11_36_o_ap_vld;
reg kernel_data_V_11_28_ap_vld;
reg[15:0] kernel_data_V_11_37_o;
reg kernel_data_V_11_37_o_ap_vld;
reg kernel_data_V_11_29_ap_vld;
reg[15:0] kernel_data_V_11_38_o;
reg kernel_data_V_11_38_o_ap_vld;
reg kernel_data_V_11_30_ap_vld;
reg[15:0] kernel_data_V_11_39_o;
reg kernel_data_V_11_39_o_ap_vld;
reg kernel_data_V_11_31_ap_vld;
reg[15:0] kernel_data_V_11_56_o;
reg kernel_data_V_11_56_o_ap_vld;
reg kernel_data_V_11_48_ap_vld;
reg[15:0] kernel_data_V_11_57_o;
reg kernel_data_V_11_57_o_ap_vld;
reg kernel_data_V_11_49_ap_vld;
reg[15:0] kernel_data_V_11_58_o;
reg kernel_data_V_11_58_o_ap_vld;
reg kernel_data_V_11_50_ap_vld;
reg[15:0] kernel_data_V_11_59_o;
reg kernel_data_V_11_59_o_ap_vld;
reg kernel_data_V_11_51_ap_vld;
reg[15:0] kernel_data_V_11_60_o;
reg kernel_data_V_11_60_o_ap_vld;
reg kernel_data_V_11_52_ap_vld;
reg[15:0] kernel_data_V_11_61_o;
reg kernel_data_V_11_61_o_ap_vld;
reg kernel_data_V_11_53_ap_vld;
reg[15:0] kernel_data_V_11_62_o;
reg kernel_data_V_11_62_o_ap_vld;
reg kernel_data_V_11_54_ap_vld;
reg[15:0] kernel_data_V_11_63_o;
reg kernel_data_V_11_63_o_ap_vld;
reg kernel_data_V_11_55_ap_vld;
reg[15:0] kernel_data_V_11_16_o;
reg kernel_data_V_11_16_o_ap_vld;
reg[15:0] kernel_data_V_11_17_o;
reg kernel_data_V_11_17_o_ap_vld;
reg[15:0] kernel_data_V_11_18_o;
reg kernel_data_V_11_18_o_ap_vld;
reg[15:0] kernel_data_V_11_19_o;
reg kernel_data_V_11_19_o_ap_vld;
reg[15:0] kernel_data_V_11_20_o;
reg kernel_data_V_11_20_o_ap_vld;
reg[15:0] kernel_data_V_11_21_o;
reg kernel_data_V_11_21_o_ap_vld;
reg[15:0] kernel_data_V_11_22_o;
reg kernel_data_V_11_22_o_ap_vld;
reg[15:0] kernel_data_V_11_23_o;
reg kernel_data_V_11_23_o_ap_vld;
reg[15:0] kernel_data_V_11_40_o;
reg kernel_data_V_11_40_o_ap_vld;
reg[15:0] kernel_data_V_11_41_o;
reg kernel_data_V_11_41_o_ap_vld;
reg[15:0] kernel_data_V_11_42_o;
reg kernel_data_V_11_42_o_ap_vld;
reg[15:0] kernel_data_V_11_43_o;
reg kernel_data_V_11_43_o_ap_vld;
reg[15:0] kernel_data_V_11_44_o;
reg kernel_data_V_11_44_o_ap_vld;
reg[15:0] kernel_data_V_11_45_o;
reg kernel_data_V_11_45_o_ap_vld;
reg[15:0] kernel_data_V_11_46_o;
reg kernel_data_V_11_46_o_ap_vld;
reg[15:0] kernel_data_V_11_47_o;
reg kernel_data_V_11_47_o_ap_vld;
reg[15:0] kernel_data_V_11_64_o;
reg kernel_data_V_11_64_o_ap_vld;
reg[15:0] kernel_data_V_11_65_o;
reg kernel_data_V_11_65_o_ap_vld;
reg[15:0] kernel_data_V_11_66_o;
reg kernel_data_V_11_66_o_ap_vld;
reg[15:0] kernel_data_V_11_67_o;
reg kernel_data_V_11_67_o_ap_vld;
reg[15:0] kernel_data_V_11_68_o;
reg kernel_data_V_11_68_o_ap_vld;
reg[15:0] kernel_data_V_11_69_o;
reg kernel_data_V_11_69_o_ap_vld;
reg[15:0] kernel_data_V_11_70_o;
reg kernel_data_V_11_70_o_ap_vld;
reg[15:0] kernel_data_V_11_71_o;
reg kernel_data_V_11_71_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    line_buffer_Array_11_0_0_ce0;
reg    line_buffer_Array_11_0_0_we0;
wire   [15:0] line_buffer_Array_11_0_0_q0;
reg    line_buffer_Array_11_1_0_ce0;
reg    line_buffer_Array_11_1_0_we0;
wire   [15:0] line_buffer_Array_11_1_0_q0;
reg    line_buffer_Array_11_0_1_ce0;
reg    line_buffer_Array_11_0_1_we0;
wire   [15:0] line_buffer_Array_11_0_1_q0;
reg    line_buffer_Array_11_1_1_ce0;
reg    line_buffer_Array_11_1_1_we0;
wire   [15:0] line_buffer_Array_11_1_1_q0;
reg    line_buffer_Array_11_0_2_ce0;
reg    line_buffer_Array_11_0_2_we0;
wire   [15:0] line_buffer_Array_11_0_2_q0;
reg    line_buffer_Array_11_1_2_ce0;
reg    line_buffer_Array_11_1_2_we0;
wire   [15:0] line_buffer_Array_11_1_2_q0;
reg    line_buffer_Array_11_0_3_ce0;
reg    line_buffer_Array_11_0_3_we0;
wire   [15:0] line_buffer_Array_11_0_3_q0;
reg    line_buffer_Array_11_1_3_ce0;
reg    line_buffer_Array_11_1_3_we0;
wire   [15:0] line_buffer_Array_11_1_3_q0;
reg    line_buffer_Array_11_0_4_ce0;
reg    line_buffer_Array_11_0_4_we0;
wire   [15:0] line_buffer_Array_11_0_4_q0;
reg    line_buffer_Array_11_1_4_ce0;
reg    line_buffer_Array_11_1_4_we0;
wire   [15:0] line_buffer_Array_11_1_4_q0;
reg    line_buffer_Array_11_0_5_ce0;
reg    line_buffer_Array_11_0_5_we0;
wire   [15:0] line_buffer_Array_11_0_5_q0;
reg    line_buffer_Array_11_1_5_ce0;
reg    line_buffer_Array_11_1_5_we0;
wire   [15:0] line_buffer_Array_11_1_5_q0;
reg    line_buffer_Array_11_0_6_ce0;
reg    line_buffer_Array_11_0_6_we0;
wire   [15:0] line_buffer_Array_11_0_6_q0;
reg    line_buffer_Array_11_1_6_ce0;
reg    line_buffer_Array_11_1_6_we0;
wire   [15:0] line_buffer_Array_11_1_6_q0;
reg    line_buffer_Array_11_0_7_ce0;
reg    line_buffer_Array_11_0_7_we0;
wire   [15:0] line_buffer_Array_11_0_7_q0;
reg    line_buffer_Array_11_1_7_ce0;
reg    line_buffer_Array_11_1_7_we0;
wire   [15:0] line_buffer_Array_11_1_7_q0;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
end

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_0_ce0),
    .we0(line_buffer_Array_11_0_0_we0),
    .d0(p_read),
    .q0(line_buffer_Array_11_0_0_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_0_ce0),
    .we0(line_buffer_Array_11_1_0_we0),
    .d0(line_buffer_Array_11_0_0_q0),
    .q0(line_buffer_Array_11_1_0_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_1_ce0),
    .we0(line_buffer_Array_11_0_1_we0),
    .d0(p_read1),
    .q0(line_buffer_Array_11_0_1_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_1_ce0),
    .we0(line_buffer_Array_11_1_1_we0),
    .d0(line_buffer_Array_11_0_1_q0),
    .q0(line_buffer_Array_11_1_1_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_2_ce0),
    .we0(line_buffer_Array_11_0_2_we0),
    .d0(p_read2),
    .q0(line_buffer_Array_11_0_2_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_2_ce0),
    .we0(line_buffer_Array_11_1_2_we0),
    .d0(line_buffer_Array_11_0_2_q0),
    .q0(line_buffer_Array_11_1_2_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_3_ce0),
    .we0(line_buffer_Array_11_0_3_we0),
    .d0(p_read3),
    .q0(line_buffer_Array_11_0_3_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_3_ce0),
    .we0(line_buffer_Array_11_1_3_we0),
    .d0(line_buffer_Array_11_0_3_q0),
    .q0(line_buffer_Array_11_1_3_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_4_ce0),
    .we0(line_buffer_Array_11_0_4_we0),
    .d0(p_read4),
    .q0(line_buffer_Array_11_0_4_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_4_ce0),
    .we0(line_buffer_Array_11_1_4_we0),
    .d0(line_buffer_Array_11_0_4_q0),
    .q0(line_buffer_Array_11_1_4_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_5_ce0),
    .we0(line_buffer_Array_11_0_5_we0),
    .d0(p_read5),
    .q0(line_buffer_Array_11_0_5_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_5_ce0),
    .we0(line_buffer_Array_11_1_5_we0),
    .d0(line_buffer_Array_11_0_5_q0),
    .q0(line_buffer_Array_11_1_5_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_6_ce0),
    .we0(line_buffer_Array_11_0_6_we0),
    .d0(p_read6),
    .q0(line_buffer_Array_11_0_6_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_6_ce0),
    .we0(line_buffer_Array_11_1_6_we0),
    .d0(line_buffer_Array_11_0_6_q0),
    .q0(line_buffer_Array_11_1_6_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_0_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_0_7_ce0),
    .we0(line_buffer_Array_11_0_7_we0),
    .d0(p_read7),
    .q0(line_buffer_Array_11_0_7_q0)
);

myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s_line_buffer_Array_11ibs #(
    .DataWidth( 16 ),
    .AddressRange( 62 ),
    .AddressWidth( 6 ))
line_buffer_Array_11_1_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(6'd61),
    .ce0(line_buffer_Array_11_1_7_ce0),
    .we0(line_buffer_Array_11_1_7_we0),
    .d0(line_buffer_Array_11_0_7_q0),
    .q0(line_buffer_Array_11_1_7_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_0_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_10_o = kernel_data_V_11_18_i;
    end else begin
        kernel_data_V_11_10_o = kernel_data_V_11_10_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_10_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_11_o = kernel_data_V_11_19_i;
    end else begin
        kernel_data_V_11_11_o = kernel_data_V_11_11_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_11_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_12_o = kernel_data_V_11_20_i;
    end else begin
        kernel_data_V_11_12_o = kernel_data_V_11_12_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_12_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_13_o = kernel_data_V_11_21_i;
    end else begin
        kernel_data_V_11_13_o = kernel_data_V_11_13_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_13_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_14_o = kernel_data_V_11_22_i;
    end else begin
        kernel_data_V_11_14_o = kernel_data_V_11_14_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_14_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_15_o = kernel_data_V_11_23_i;
    end else begin
        kernel_data_V_11_15_o = kernel_data_V_11_15_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_15_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_16_o = line_buffer_Array_11_1_0_q0;
    end else begin
        kernel_data_V_11_16_o = kernel_data_V_11_16_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_16_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_16_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_17_o = line_buffer_Array_11_1_1_q0;
    end else begin
        kernel_data_V_11_17_o = kernel_data_V_11_17_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_17_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_17_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_18_o = line_buffer_Array_11_1_2_q0;
    end else begin
        kernel_data_V_11_18_o = kernel_data_V_11_18_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_18_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_18_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_19_o = line_buffer_Array_11_1_3_q0;
    end else begin
        kernel_data_V_11_19_o = kernel_data_V_11_19_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_19_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_19_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_1_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_20_o = line_buffer_Array_11_1_4_q0;
    end else begin
        kernel_data_V_11_20_o = kernel_data_V_11_20_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_20_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_20_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_21_o = line_buffer_Array_11_1_5_q0;
    end else begin
        kernel_data_V_11_21_o = kernel_data_V_11_21_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_21_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_21_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_22_o = line_buffer_Array_11_1_6_q0;
    end else begin
        kernel_data_V_11_22_o = kernel_data_V_11_22_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_22_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_22_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_23_o = line_buffer_Array_11_1_7_q0;
    end else begin
        kernel_data_V_11_23_o = kernel_data_V_11_23_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_23_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_23_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_24_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_25_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_26_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_27_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_28_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_29_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_2_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_30_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_31_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_32_o = kernel_data_V_11_40_i;
    end else begin
        kernel_data_V_11_32_o = kernel_data_V_11_32_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_32_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_32_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_33_o = kernel_data_V_11_41_i;
    end else begin
        kernel_data_V_11_33_o = kernel_data_V_11_33_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_33_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_33_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_34_o = kernel_data_V_11_42_i;
    end else begin
        kernel_data_V_11_34_o = kernel_data_V_11_34_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_34_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_34_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_35_o = kernel_data_V_11_43_i;
    end else begin
        kernel_data_V_11_35_o = kernel_data_V_11_35_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_35_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_35_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_36_o = kernel_data_V_11_44_i;
    end else begin
        kernel_data_V_11_36_o = kernel_data_V_11_36_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_36_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_36_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_37_o = kernel_data_V_11_45_i;
    end else begin
        kernel_data_V_11_37_o = kernel_data_V_11_37_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_37_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_37_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_38_o = kernel_data_V_11_46_i;
    end else begin
        kernel_data_V_11_38_o = kernel_data_V_11_38_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_38_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_38_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_39_o = kernel_data_V_11_47_i;
    end else begin
        kernel_data_V_11_39_o = kernel_data_V_11_39_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_39_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_39_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_3_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_40_o = line_buffer_Array_11_0_0_q0;
    end else begin
        kernel_data_V_11_40_o = kernel_data_V_11_40_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_40_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_40_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_41_o = line_buffer_Array_11_0_1_q0;
    end else begin
        kernel_data_V_11_41_o = kernel_data_V_11_41_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_41_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_41_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_42_o = line_buffer_Array_11_0_2_q0;
    end else begin
        kernel_data_V_11_42_o = kernel_data_V_11_42_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_42_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_42_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_43_o = line_buffer_Array_11_0_3_q0;
    end else begin
        kernel_data_V_11_43_o = kernel_data_V_11_43_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_43_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_43_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_44_o = line_buffer_Array_11_0_4_q0;
    end else begin
        kernel_data_V_11_44_o = kernel_data_V_11_44_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_44_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_44_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_45_o = line_buffer_Array_11_0_5_q0;
    end else begin
        kernel_data_V_11_45_o = kernel_data_V_11_45_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_45_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_45_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_46_o = line_buffer_Array_11_0_6_q0;
    end else begin
        kernel_data_V_11_46_o = kernel_data_V_11_46_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_46_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_46_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_47_o = line_buffer_Array_11_0_7_q0;
    end else begin
        kernel_data_V_11_47_o = kernel_data_V_11_47_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_47_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_47_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_48_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_49_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_4_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_50_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_51_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_52_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_53_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_54_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_55_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_56_o = kernel_data_V_11_64_i;
    end else begin
        kernel_data_V_11_56_o = kernel_data_V_11_56_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_56_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_56_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_57_o = kernel_data_V_11_65_i;
    end else begin
        kernel_data_V_11_57_o = kernel_data_V_11_57_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_57_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_57_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_58_o = kernel_data_V_11_66_i;
    end else begin
        kernel_data_V_11_58_o = kernel_data_V_11_58_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_58_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_58_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_59_o = kernel_data_V_11_67_i;
    end else begin
        kernel_data_V_11_59_o = kernel_data_V_11_59_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_59_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_59_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_5_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_60_o = kernel_data_V_11_68_i;
    end else begin
        kernel_data_V_11_60_o = kernel_data_V_11_60_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_60_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_60_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_61_o = kernel_data_V_11_69_i;
    end else begin
        kernel_data_V_11_61_o = kernel_data_V_11_61_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_61_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_61_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_62_o = kernel_data_V_11_70_i;
    end else begin
        kernel_data_V_11_62_o = kernel_data_V_11_62_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_62_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_62_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_63_o = kernel_data_V_11_71_i;
    end else begin
        kernel_data_V_11_63_o = kernel_data_V_11_63_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_63_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_63_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_64_o = p_read;
    end else begin
        kernel_data_V_11_64_o = kernel_data_V_11_64_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_64_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_64_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_65_o = p_read1;
    end else begin
        kernel_data_V_11_65_o = kernel_data_V_11_65_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_65_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_65_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_66_o = p_read2;
    end else begin
        kernel_data_V_11_66_o = kernel_data_V_11_66_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_66_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_66_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_67_o = p_read3;
    end else begin
        kernel_data_V_11_67_o = kernel_data_V_11_67_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_67_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_67_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_68_o = p_read4;
    end else begin
        kernel_data_V_11_68_o = kernel_data_V_11_68_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_68_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_68_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_69_o = p_read5;
    end else begin
        kernel_data_V_11_69_o = kernel_data_V_11_69_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_69_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_69_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_6_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_70_o = p_read6;
    end else begin
        kernel_data_V_11_70_o = kernel_data_V_11_70_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_70_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_70_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_71_o = p_read7;
    end else begin
        kernel_data_V_11_71_o = kernel_data_V_11_71_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_71_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_71_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_7_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_8_o = kernel_data_V_11_16_i;
    end else begin
        kernel_data_V_11_8_o = kernel_data_V_11_8_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_8_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        kernel_data_V_11_9_o = kernel_data_V_11_17_i;
    end else begin
        kernel_data_V_11_9_o = kernel_data_V_11_9_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        kernel_data_V_11_9_o_ap_vld = 1'b1;
    end else begin
        kernel_data_V_11_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_1_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_1_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_2_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_2_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_3_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_3_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_4_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_4_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_5_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_5_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_6_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_6_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_7_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_0_7_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_0_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_1_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_1_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_2_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_2_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_3_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_3_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_4_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_4_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_5_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_5_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_6_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_6_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_7_ce0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_buffer_Array_11_1_7_we0 = 1'd1;
    end else begin
        line_buffer_Array_11_1_7_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign kernel_data_V_11_0 = kernel_data_V_11_8_i;

assign kernel_data_V_11_1 = kernel_data_V_11_9_i;

assign kernel_data_V_11_2 = kernel_data_V_11_10_i;

assign kernel_data_V_11_24 = kernel_data_V_11_32_i;

assign kernel_data_V_11_25 = kernel_data_V_11_33_i;

assign kernel_data_V_11_26 = kernel_data_V_11_34_i;

assign kernel_data_V_11_27 = kernel_data_V_11_35_i;

assign kernel_data_V_11_28 = kernel_data_V_11_36_i;

assign kernel_data_V_11_29 = kernel_data_V_11_37_i;

assign kernel_data_V_11_3 = kernel_data_V_11_11_i;

assign kernel_data_V_11_30 = kernel_data_V_11_38_i;

assign kernel_data_V_11_31 = kernel_data_V_11_39_i;

assign kernel_data_V_11_4 = kernel_data_V_11_12_i;

assign kernel_data_V_11_48 = kernel_data_V_11_56_i;

assign kernel_data_V_11_49 = kernel_data_V_11_57_i;

assign kernel_data_V_11_5 = kernel_data_V_11_13_i;

assign kernel_data_V_11_50 = kernel_data_V_11_58_i;

assign kernel_data_V_11_51 = kernel_data_V_11_59_i;

assign kernel_data_V_11_52 = kernel_data_V_11_60_i;

assign kernel_data_V_11_53 = kernel_data_V_11_61_i;

assign kernel_data_V_11_54 = kernel_data_V_11_62_i;

assign kernel_data_V_11_55 = kernel_data_V_11_63_i;

assign kernel_data_V_11_6 = kernel_data_V_11_14_i;

assign kernel_data_V_11_7 = kernel_data_V_11_15_i;

endmodule //myproject_shift_line_buffer_array_ap_fixed_16_3_5_3_0_8u_config6_s
