// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_3_5_3_0_8u_relu_config25_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_dout,
        data_empty_n,
        data_read,
        res_din,
        res_full_n,
        res_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] data_dout;
input   data_empty_n;
output   data_read;
output  [127:0] res_din;
input   res_full_n;
output   res_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_read;
reg res_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln41_reg_424;
reg    res_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln41_reg_424_pp0_iter1_reg;
reg   [11:0] i_reg_117;
wire   [11:0] i_2_fu_128_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln41_fu_134_p2;
wire   [15:0] out_data_16_fu_230_p3;
reg   [15:0] out_data_16_reg_428;
wire   [15:0] out_data_17_fu_254_p3;
reg   [15:0] out_data_17_reg_433;
wire   [15:0] out_data_19_fu_278_p3;
reg   [15:0] out_data_19_reg_438;
wire   [15:0] out_data_21_fu_302_p3;
reg   [15:0] out_data_21_reg_443;
wire   [15:0] out_data_23_fu_326_p3;
reg   [15:0] out_data_23_reg_448;
wire   [15:0] out_data_25_fu_350_p3;
reg   [15:0] out_data_25_reg_453;
wire   [15:0] out_data_27_fu_374_p3;
reg   [15:0] out_data_27_reg_458;
wire   [15:0] out_data_29_fu_398_p3;
reg   [15:0] out_data_29_reg_463;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire   [41:0] trunc_ln145_fu_140_p1;
wire   [0:0] icmp_ln1494_fu_214_p2;
wire   [15:0] out_data_fu_220_p4;
wire   [41:0] trunc_ln145_s_fu_144_p4;
wire   [0:0] icmp_ln1494_4_fu_238_p2;
wire   [15:0] out_data_9_fu_244_p4;
wire   [41:0] trunc_ln145_7_fu_154_p4;
wire   [0:0] icmp_ln1494_5_fu_262_p2;
wire   [15:0] out_data_18_fu_268_p4;
wire   [41:0] trunc_ln145_8_fu_164_p4;
wire   [0:0] icmp_ln1494_6_fu_286_p2;
wire   [15:0] out_data_20_fu_292_p4;
wire   [41:0] trunc_ln145_9_fu_174_p4;
wire   [0:0] icmp_ln1494_7_fu_310_p2;
wire   [15:0] out_data_22_fu_316_p4;
wire   [41:0] trunc_ln145_1_fu_184_p4;
wire   [0:0] icmp_ln1494_8_fu_334_p2;
wire   [15:0] out_data_24_fu_340_p4;
wire   [41:0] trunc_ln145_2_fu_194_p4;
wire   [0:0] icmp_ln1494_9_fu_358_p2;
wire   [15:0] out_data_26_fu_364_p4;
wire   [41:0] trunc_ln145_3_fu_204_p4;
wire   [0:0] icmp_ln1494_10_fu_382_p2;
wire   [15:0] out_data_28_fu_388_p4;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_117 <= i_2_fu_128_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_117 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln41_reg_424 <= icmp_ln41_fu_134_p2;
        icmp_ln41_reg_424_pp0_iter1_reg <= icmp_ln41_reg_424;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_424 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_data_16_reg_428 <= out_data_16_fu_230_p3;
        out_data_17_reg_433 <= out_data_17_fu_254_p3;
        out_data_19_reg_438 <= out_data_19_fu_278_p3;
        out_data_21_reg_443 <= out_data_21_fu_302_p3;
        out_data_23_reg_448 <= out_data_23_fu_326_p3;
        out_data_25_reg_453 <= out_data_25_fu_350_p3;
        out_data_27_reg_458 <= out_data_27_fu_374_p3;
        out_data_29_reg_463 <= out_data_29_fu_398_p3;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_134_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_424 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_blk_n = data_empty_n;
    end else begin
        data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_424 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_read = 1'b1;
    end else begin
        data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        res_blk_n = res_full_n;
    end else begin
        res_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_write = 1'b1;
    end else begin
        res_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln41_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((icmp_ln41_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_424 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_424 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (res_full_n == 1'b0)) | ((icmp_ln41_reg_424 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (data_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln41_reg_424 == 1'd0) & (data_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((icmp_ln41_reg_424_pp0_iter1_reg == 1'd0) & (res_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign i_2_fu_128_p2 = (i_reg_117 + 12'd1);

assign icmp_ln1494_10_fu_382_p2 = (($signed(trunc_ln145_3_fu_204_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_238_p2 = (($signed(trunc_ln145_s_fu_144_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_262_p2 = (($signed(trunc_ln145_7_fu_154_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_286_p2 = (($signed(trunc_ln145_8_fu_164_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_310_p2 = (($signed(trunc_ln145_9_fu_174_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_334_p2 = (($signed(trunc_ln145_1_fu_184_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_358_p2 = (($signed(trunc_ln145_2_fu_194_p4) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_214_p2 = (($signed(trunc_ln145_fu_140_p1) > $signed(42'd0)) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_134_p2 = ((i_reg_117 == 12'd2704) ? 1'b1 : 1'b0);

assign out_data_16_fu_230_p3 = ((icmp_ln1494_fu_214_p2[0:0] == 1'b1) ? out_data_fu_220_p4 : 16'd0);

assign out_data_17_fu_254_p3 = ((icmp_ln1494_4_fu_238_p2[0:0] == 1'b1) ? out_data_9_fu_244_p4 : 16'd0);

assign out_data_18_fu_268_p4 = {{data_dout[156:141]}};

assign out_data_19_fu_278_p3 = ((icmp_ln1494_5_fu_262_p2[0:0] == 1'b1) ? out_data_18_fu_268_p4 : 16'd0);

assign out_data_20_fu_292_p4 = {{data_dout[220:205]}};

assign out_data_21_fu_302_p3 = ((icmp_ln1494_6_fu_286_p2[0:0] == 1'b1) ? out_data_20_fu_292_p4 : 16'd0);

assign out_data_22_fu_316_p4 = {{data_dout[284:269]}};

assign out_data_23_fu_326_p3 = ((icmp_ln1494_7_fu_310_p2[0:0] == 1'b1) ? out_data_22_fu_316_p4 : 16'd0);

assign out_data_24_fu_340_p4 = {{data_dout[348:333]}};

assign out_data_25_fu_350_p3 = ((icmp_ln1494_8_fu_334_p2[0:0] == 1'b1) ? out_data_24_fu_340_p4 : 16'd0);

assign out_data_26_fu_364_p4 = {{data_dout[412:397]}};

assign out_data_27_fu_374_p3 = ((icmp_ln1494_9_fu_358_p2[0:0] == 1'b1) ? out_data_26_fu_364_p4 : 16'd0);

assign out_data_28_fu_388_p4 = {{data_dout[476:461]}};

assign out_data_29_fu_398_p3 = ((icmp_ln1494_10_fu_382_p2[0:0] == 1'b1) ? out_data_28_fu_388_p4 : 16'd0);

assign out_data_9_fu_244_p4 = {{data_dout[92:77]}};

assign out_data_fu_220_p4 = {{data_dout[28:13]}};

assign res_din = {{{{{{{{out_data_29_reg_463}, {out_data_27_reg_458}}, {out_data_25_reg_453}}, {out_data_23_reg_448}}, {out_data_21_reg_443}}, {out_data_19_reg_438}}, {out_data_17_reg_433}}, {out_data_16_reg_428}};

assign start_out = real_start;

assign trunc_ln145_1_fu_184_p4 = {{data_dout[361:320]}};

assign trunc_ln145_2_fu_194_p4 = {{data_dout[425:384]}};

assign trunc_ln145_3_fu_204_p4 = {{data_dout[489:448]}};

assign trunc_ln145_7_fu_154_p4 = {{data_dout[169:128]}};

assign trunc_ln145_8_fu_164_p4 = {{data_dout[233:192]}};

assign trunc_ln145_9_fu_174_p4 = {{data_dout[297:256]}};

assign trunc_ln145_fu_140_p1 = data_dout[41:0];

assign trunc_ln145_s_fu_144_p4 = {{data_dout[105:64]}};

endmodule //myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_3_5_3_0_8u_relu_config25_s
