// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_14_5_3_0_16u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer5_out_dout,
        layer5_out_empty_n,
        layer5_out_read,
        layer6_out_din,
        layer6_out_full_n,
        layer6_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer5_out_dout;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [1023:0] layer6_out_din;
input   layer6_out_full_n;
output   layer6_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer5_out_read;
reg layer6_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer5_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_475_p2;
wire   [11:0] add_ln51_fu_469_p2;
reg   [11:0] add_ln51_reg_563;
reg    ap_block_state2;
wire   [15:0] trunc_ln145_fu_481_p1;
reg   [15:0] trunc_ln145_reg_571;
reg   [15:0] trunc_ln145_s_reg_576;
reg   [15:0] trunc_ln145_110_reg_581;
reg   [15:0] trunc_ln145_111_reg_586;
reg   [15:0] trunc_ln145_112_reg_591;
reg   [15:0] trunc_ln145_113_reg_596;
reg   [15:0] trunc_ln145_114_reg_601;
reg   [15:0] trunc_ln145_115_reg_606;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready;
wire   [1023:0] grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write;
reg   [11:0] indvar_flatten_reg_256;
reg    ap_block_state1;
wire    ap_CS_fsm_state3;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg;
reg    ap_block_state2_ignore_call12;
reg   [2:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready),
    .layer6_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write),
    .p_read(trunc_ln145_reg_571),
    .p_read1(trunc_ln145_s_reg_576),
    .p_read2(trunc_ln145_110_reg_581),
    .p_read3(trunc_ln145_111_reg_586),
    .p_read4(trunc_ln145_112_reg_591),
    .p_read5(trunc_ln145_113_reg_596),
    .p_read6(trunc_ln145_114_reg_601),
    .p_read7(trunc_ln145_115_reg_606)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten_reg_256 <= add_ln51_reg_563;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_256 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln51_reg_563 <= add_ln51_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln145_110_reg_581 <= {{layer5_out_dout[47:32]}};
        trunc_ln145_111_reg_586 <= {{layer5_out_dout[63:48]}};
        trunc_ln145_112_reg_591 <= {{layer5_out_dout[79:64]}};
        trunc_ln145_113_reg_596 <= {{layer5_out_dout[95:80]}};
        trunc_ln145_114_reg_601 <= {{layer5_out_dout[111:96]}};
        trunc_ln145_115_reg_606 <= {{layer5_out_dout[127:112]}};
        trunc_ln145_reg_571 <= trunc_ln145_fu_481_p1;
        trunc_ln145_s_reg_576 <= {{layer5_out_dout[31:16]}};
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer6_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_write;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0)) & (icmp_ln51_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_469_p2 = (indvar_flatten_reg_256 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call12 = ((icmp_ln51_fu_475_p2 == 1'd0) & (layer5_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_ap_start_reg;

assign icmp_ln51_fu_475_p2 = ((indvar_flatten_reg_256 == 12'd3844) ? 1'b1 : 1'b0);

assign layer6_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_40_14_5_3_0_16u_config6_s_fu_267_layer6_out_din;

assign start_out = real_start;

assign trunc_ln145_fu_481_p1 = layer5_out_dout[15:0];

endmodule //myproject_conv_2d_cl_array_ap_fixed_8u_array_ap_fixed_40_14_5_3_0_16u_config6_s
